name: microdrop

channels:
- alexsk
- conda-forge
- binstar
- vignesh229
- dropbot

dependencies:
- apptools
- dramatiq
- dropbot
- vignesh229::envisage
- vignesh229::mr-box-peripheral-board
- nptyping
- pyface
- pyside6
- pytest
- shapely
- pydantic
- traits
- traitsui
- binstar::redis-server
- redis-py
- apscheduler
- networkx
- ipython
- tqdm
- pyqtgraph