# (C) Copyright 2024-2026 Blue Ocean Technologies, Inc., Toronto, ON
# All rights reserved.
#
# This software is provided without warranty under the terms of the AGPL-3.0
# license included in LICENSE and may be redistributed only under the
# conditions described in the aforementioned license. The license is also
# available online at https://www.gnu.org/licenses/agpl-3.0.txt
#
# Thanks for using Microdrop open source!

"""Build a tutorial source page into one self-contained, offline HTML file.

Reads ``<slug>.src.html`` (content only, see ``README.md`` next to this
script), inlines the shared kit CSS/JS, the traced toolbar glyphs and any
local figures, and writes ``<slug>.html`` next to it unless an output path is
given. The previous build doubles as the glyph cache (its ``<symbol>``
elements keep the font text they were traced from), so a rebuild is
deterministic and needs Qt only when a new glyph appears. From ``src``::

    pixi run python -m examples.tutorials.build_tutorial <src> [out]
    pixi run python -m examples.tutorials.build_tutorial <src> --check

``--check`` rebuilds in memory and fails when the committed output is stale.
Set ``QT_QPA_PLATFORM=offscreen`` to trace glyphs without a display.
"""

# Standard library imports.
import argparse
import base64
import html
import mimetypes
import re
import sys
from html.parser import HTMLParser
from pathlib import Path

# Microdrop style imports.
from microdrop_style.tutorial import TUTORIAL_CSS_PATH, TUTORIAL_JS_PATH
from microdrop_style.tutorial.glyphs import (
    glyph_id,
    glyph_text,
    read_symbols,
    symbol_markup,
    trace_glyphs,
)

# Logger import.
from logger.logger_service import get_logger

logger = get_logger(__name__)

SOURCE_SUFFIX = ".src.html"
#: Built pages above this size get a warning; the reference guide is ~260 KB.
SIZE_BUDGET_BYTES = 300_000

#: A tag attribute or CSS rule that would make the page fetch at load time.
NETWORK_REFERENCE_PATTERN = re.compile(
    r"""(?:src|href)\s*=\s*["']?\s*(?:https?:)?//"""
    r"""|url\(\s*["']?\s*(?:https?:)?//|@import"""
)
GLYPH_REFERENCE_PATTERN = re.compile(r"""href=["']#ic-([A-Za-z0-9_]+)["']""")

#: Term-card fact divs and their default labels, in reading order.
FACT_LABELS = {
    "data-what": "What it is",
    "data-when": "When to use it",
    "data-read": "How to read it",
    "data-typical": "Typical value",
    "data-fact": "",
}
VOID_TAGS = {
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "link",
    "meta",
    "source",
    "track",
    "wbr",
}
DROPPED_TAGS = {"html", "head", "body"}

PAGE_TEMPLATE = """<!DOCTYPE html>
{header}<!--
  Built by examples/tutorials/build_tutorial.py from {source_name}.
  Edit the source and rebuild; do not edit this file by hand.

  Self-contained on purpose: no network, no external fonts or images, so it
  opens offline in the Help dialog (QtWebEngine) and in a plain browser.
-->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
{css}</style>
</head>
<body>
{glyphs}{mobile_contents}<div class="{layout_class}">
{contents}<main>
{body}
</main>
</div>
<script>
{js}</script>
{scripts}</body>
</html>
"""


class TutorialBuildError(ValueError):
    """A tutorial source that cannot be built as written."""


def _attrs_markup(attrs):
    """Serialize ``(name, value)`` pairs back into start-tag attributes."""
    parts = []

    for name, value in attrs:
        if value is None:
            parts.append(f" {name}")
        else:
            parts.append(f' {name}="{html.escape(value, quote=True)}"')

    return "".join(parts)


def _with_class(attrs, class_name):
    """Return ``attrs`` with ``class_name`` prepended to its class list."""
    existing = dict(attrs).get("class")
    merged = f"{class_name} {existing}" if existing else class_name
    kept = [(name, value) for name, value in attrs if name != "class"]

    return [("class", merged), *kept]


class _Frame:
    """One open element of the source, with the role the build gave it."""

    def __init__(self, tag, role=None, **state):
        self.tag = tag
        self.role = role
        self.__dict__.update(state)


class _SourceRewriter(HTMLParser):
    """Stream the source through, rewriting the authoring attributes.

    Everything not listed in ``README.md`` passes through verbatim; the
    rewritten elements must be closed explicitly.
    """

    def __init__(self, base_dir):
        super().__init__(convert_charrefs=False)
        self.base_dir = base_dir
        self.out = []
        self.header_comments = []
        self.title = None
        self.styles = []
        self.scripts = []
        #: Glyph id -> name as written (``ICON_*`` or a ligature).
        self.glyphs = {}
        self.parts = []
        self.wants_contents = False
        self.stack = []
        self._seen_tag = False
        self._suppress = 0

    # ------------------------------------------------------------ helpers
    def _emit(self, markup):
        # Heading text is mirrored into the contents as it is emitted.
        for frame in self.stack:
            if frame.role == "heading":
                frame.text.append(markup)

        if not self._suppress:
            self.out.append(markup)

    def _term(self):
        for frame in reversed(self.stack):
            if frame.role == "term":
                return frame

        return None

    def _part(self):
        for frame in reversed(self.stack):
            if frame.role == "part":
                return frame

        return None

    def _close_facts(self, term):
        if term is not None and term.facts_open:
            self._emit("</dl>")
            term.facts_open = False

    def _is_term_child(self):
        return bool(self.stack) and self.stack[-1].role == "term"

    # ------------------------------------------------------------ parser hooks
    def handle_decl(self, decl):
        pass

    def handle_comment(self, data):
        if not self._seen_tag:
            self.header_comments.append(f"<!--{data}-->\n")

            return

        self._emit(f"<!--{data}-->")

    def handle_startendtag(self, tag, attrs):
        self._start(tag, attrs, self_closing=True)

    def handle_starttag(self, tag, attrs):
        self._start(tag, attrs, self_closing=False)

    def handle_endtag(self, tag):
        if tag in DROPPED_TAGS or tag in VOID_TAGS:
            return

        if not any(frame.tag == tag for frame in self.stack):
            raise TutorialBuildError(f"Unmatched </{tag}> at line {self.getpos()[0]}")

        while self.stack:
            frame = self.stack.pop()
            self._end(frame, emit_tag=frame.tag == tag)

            if frame.tag == tag:
                break

    def handle_data(self, data):
        if self.stack and self.stack[-1].role in ("title", "style", "script"):
            self.stack[-1].text.append(data)

            return

        if self._is_term_child() and data.strip():
            self._close_facts(self.stack[-1])

        self._emit(data)

    def handle_entityref(self, name):
        self.handle_data(f"&{name};")

    def handle_charref(self, name):
        self.handle_data(f"&#{name};")

    # ------------------------------------------------------------ rewriting
    def _start(self, tag, attrs, self_closing):
        self._seen_tag = True

        if tag in DROPPED_TAGS:
            return

        names = dict(attrs)
        markup = self.get_starttag_text()

        if self._is_term_child() and not any(name in names for name in FACT_LABELS):
            self._close_facts(self.stack[-1])

        if tag in ("title", "style", "script"):
            self.stack.append(_Frame(tag, tag, text=[]))

            return

        if tag == "img":
            self._emit(self._inline_image(attrs))

            return

        if self_closing or tag in VOID_TAGS:
            self._emit(markup)

            return

        frame = _Frame(tag)

        if tag == "nav" and "data-contents" in names:
            self.wants_contents = True
            frame.role = "suppress"
            self._suppress += 1

        elif tag == "header" and "data-hero" in names:
            kept = [(n, v) for n, v in attrs if n != "data-hero"]

            if "id" not in names:
                kept.append(("id", "start"))

            markup = f"<header{_attrs_markup(_with_class(kept, 'hero'))}>"

        elif tag == "section" and "data-part" in names:
            frame.role = "part"
            frame.entry = {"id": names.get("id"), "title": "", "terms": []}
            self.parts.append(frame.entry)
            kept = [(n, v) for n, v in attrs if n != "data-part"]
            markup = f"<section{_attrs_markup(_with_class(kept, 'part'))}>"

        elif tag == "section" and "data-term" in names:
            frame.role = "term"
            frame.where = names.get("data-where")
            frame.facts_open = False
            frame.entry = {"id": names.get("id"), "title": ""}
            part = self._part()
            (part.entry["terms"] if part else self.parts).append(frame.entry)
            kept = [(n, v) for n, v in attrs if n not in ("data-term", "data-where")]
            tag_markup = _attrs_markup(_with_class(kept, "term"))
            markup = f"<article{tag_markup}>"

        elif tag in ("h2", "h3") and self._heading_owner(tag) is not None:
            frame.role = "heading"
            frame.owner = self._heading_owner(tag)
            frame.text = []

        elif tag == "div" and self._is_term_child() and self._fact_label(attrs):
            term = self.stack[-1]
            frame.role = "fact"

            if not term.facts_open:
                self._emit('<dl class="facts">')
                term.facts_open = True

            self._emit(f"<dt>{self._fact_label(attrs)}</dt>")
            markup = "<dd>"

        elif tag == "figure" and "data-demo" in names:
            markup = f"<figure{_attrs_markup(_with_class(attrs, 'demo'))}>"

        elif tag == "i" and "data-glyph" in names:
            frame.role = "suppress"
            self._emit(self._glyph_button(names))
            self._suppress += 1
            self.stack.append(frame)

            return

        self.stack.append(frame)
        self._emit(markup)

    def _end(self, frame, emit_tag):
        if frame.role in ("title", "style", "script"):
            text = "".join(frame.text)

            if frame.role == "title":
                self.title = text.strip()
            elif frame.role == "style":
                self.styles.append(text.strip("\n") + "\n")
            else:
                self.scripts.append(text.strip("\n") + "\n")

            return

        if frame.role == "suppress":
            self._suppress -= 1

            return

        if frame.role == "heading":
            frame.owner.entry["title"] = re.sub(r"<[^>]*>", "", "".join(frame.text))
            frame.owner.titled = True

            if frame.owner.role == "term" and frame.owner.where:
                where = html.escape(frame.owner.where, quote=False)
                self._emit(f' <span class="where">{where}</span>')

        if frame.role == "term":
            self._close_facts(frame)
            self._emit("</article>")

            return

        if frame.role == "fact":
            self._emit("</dd>")

            return

        if emit_tag:
            self._emit(f"</{frame.tag}>")

    def _heading_owner(self, tag):
        """The part (for h2) or term (for h3) a heading titles, if untitled."""
        owner = self._part() if tag == "h2" else self._term()

        if owner is None or getattr(owner, "titled", False):
            return None

        return owner

    @staticmethod
    def _fact_label(attrs):
        for name, value in attrs:
            if name in FACT_LABELS:
                return html.escape(value) if value else FACT_LABELS[name]

        return None

    def _glyph_button(self, names):
        name = names["data-glyph"]
        symbol = glyph_id(name)
        self.glyphs[symbol] = name
        classes = "tbtn"

        if "data-on" in names:
            classes += " on"

        if "data-inline" in names:
            classes += " tbtn-inline"

        label = names.get("data-label")
        role = (
            f' role="img" aria-label="{html.escape(label, quote=True)}"'
            if label
            else ' aria-hidden="true"'
        )

        return (
            f'<span class="{classes}"{role}><svg class="ic" aria-hidden="true">'
            f'<use href="#ic-{symbol}"/></svg></span>'
        )

    def _inline_image(self, attrs):
        """Inline a local ``<img>``: SVG markup with ``data-inline``, else a
        data URI. Network sources are left for the reference check to fail."""
        names = dict(attrs)
        source = names.get("src", "")

        if not source or re.match(r"(?:[a-z]+:)?//|data:", source):
            return self.get_starttag_text()

        path = (self.base_dir / source).resolve()

        if not path.is_file():
            raise TutorialBuildError(f"Figure not found: {source}")

        if "data-inline" in names and path.suffix == ".svg":
            svg = path.read_text(encoding="utf-8")
            svg = re.sub(r"<\?xml[^>]*\?>|<!DOCTYPE[^>]*>", "", svg).strip()
            alt = names.get("alt")
            label = f' role="img" aria-label="{html.escape(alt, quote=True)}"'
            classes = f' class="{names["class"]}"' if "class" in names else ""

            return re.sub(r"<svg\b", f"<svg{classes}{label if alt else ''}", svg, 1)

        mime = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
        encoded = base64.b64encode(path.read_bytes()).decode("ascii")
        kept = [(n, v) for n, v in attrs if n not in ("src", "data-inline")]

        return f'<img src="data:{mime};base64,{encoded}"{_attrs_markup(kept)}>'


def _contents_markup(parts):
    """Return the sidebar ``<ol>`` for the parts and their term cards."""
    lines = ['<ol id="toc">']

    for part in parts:
        if not part["id"]:
            raise TutorialBuildError(f"Section '{part['title']}' needs an id")

        terms = part.get("terms", [])
        link = f'<a href="#{part["id"]}">{part["title"]}</a>'

        if not terms:
            lines.append(f"  <li>{link}</li>")
            continue

        lines.append(f"  <li>{link}")

        lines.append("    <ol>")

        for term in terms:
            if not term["id"]:
                raise TutorialBuildError(f"Term '{term['title']}' needs an id")

            lines.append(f'      <li><a href="#{term["id"]}">{term["title"]}</a></li>')

        lines.append("    </ol>\n  </li>")

    lines.append("</ol>")

    return "\n".join(lines)


def _glyph_defs(cache):
    """Return the hidden SVG holding one ``<symbol>`` per cached glyph."""
    if not cache:
        return ""

    symbols = "\n".join(
        f"  {symbol_markup(symbol, glyph)}" for symbol, glyph in sorted(cache.items())
    )

    return (
        '<svg width="0" height="0" style="position:absolute" aria-hidden="true" '
        'focusable="false">\n'
        "<!-- Material Symbols Outlined glyphs (Apache-2.0), traced from the font "
        "the app draws its buttons with. -->\n"
        f"<defs>\n{symbols}\n</defs>\n</svg>\n"
    )


def _resolve_glyphs(glyphs, cache, retrace):
    """Return ``cache`` limited to ``glyphs``, tracing any missing or stale."""
    wanted = {symbol: glyph_text(name) for symbol, name in glyphs.items()}
    stale = {
        symbol
        for symbol, text in wanted.items()
        if retrace or cache.get(symbol, {}).get("text") != text
    }
    resolved = {symbol: cache[symbol] for symbol in wanted if symbol not in stale}

    if stale:
        logger.info(f"Tracing glyphs: {', '.join(sorted(stale))}")
        resolved.update(trace_glyphs([glyphs[symbol] for symbol in sorted(stale)]))

    return {symbol: resolved[symbol] for symbol in sorted(resolved)}


def find_network_references(page):
    """Return every fragment of ``page`` that would load over the network."""
    return [match.group(0) for match in NETWORK_REFERENCE_PATTERN.finditer(page)]


def render_tutorial(source_text, base_dir, glyph_cache, source_name, retrace=False):
    """Render a source page; return ``(page, glyph_cache)``.

    ``glyph_cache`` maps glyph id to its traced ``{"text", "d", "viewBox"}``;
    the returned cache holds exactly the glyphs the page uses.
    """
    parser = _SourceRewriter(base_dir)
    parser.feed(source_text.replace("\r\n", "\n"))
    parser.close()

    if parser.stack:
        unclosed = ", ".join(f"<{frame.tag}>" for frame in parser.stack)
        raise TutorialBuildError(f"Unclosed elements at end of source: {unclosed}")

    if not parser.title:
        raise TutorialBuildError("The source needs a <title>")

    body = "".join(parser.out).strip("\n")
    scripts = "".join(f"<script>\n{script}</script>\n" for script in parser.scripts)
    glyphs = dict(parser.glyphs)

    for symbol in GLYPH_REFERENCE_PATTERN.findall(body + scripts):
        glyphs.setdefault(symbol, symbol)

    cache = _resolve_glyphs(glyphs, glyph_cache, retrace) if glyphs else {}
    css = TUTORIAL_CSS_PATH.read_text(encoding="utf-8").replace("\r\n", "\n")
    js = TUTORIAL_JS_PATH.read_text(encoding="utf-8").replace("\r\n", "\n")

    if parser.styles:
        css += "\n/* ---------- this tutorial ---------- */\n" + "".join(parser.styles)

    if parser.wants_contents:
        contents = (
            '<nav class="toc" aria-label="Contents">\n'
            '<p class="toc-title">Contents</p>\n'
            f"{_contents_markup(parser.parts)}\n</nav>\n"
        )
        mobile_contents = (
            '<details class="toc-mobile" id="toc-mobile">\n'
            "  <summary>Contents</summary>\n  <div data-toc-clone></div>\n"
            "</details>\n"
        )
    else:
        contents = mobile_contents = ""

    page = PAGE_TEMPLATE.format(
        header="".join(parser.header_comments),
        source_name=source_name,
        title=parser.title,
        css=css,
        glyphs=_glyph_defs(cache),
        mobile_contents=mobile_contents,
        layout_class="layout" if parser.wants_contents else "layout no-toc",
        contents=contents,
        body=body,
        js=js,
        scripts=scripts,
    )
    network = find_network_references(page)

    if network:
        raise TutorialBuildError(f"Network references in the page: {network}")

    return page, cache


def default_output_path(source_path):
    """``<slug>.src.html`` -> ``<slug>.html`` in the same folder."""
    name = source_path.name

    if not name.endswith(SOURCE_SUFFIX):
        raise TutorialBuildError(f"Source names end in {SOURCE_SUFFIX}: {name}")

    return source_path.with_name(name[: -len(SOURCE_SUFFIX)] + ".html")


def _render_file(source_path, output_path, retrace=False):
    """Render ``source_path``, reusing the glyphs the previous build of
    ``output_path`` traced; return the page text."""
    previous = output_path.read_text(encoding="utf-8") if output_path.is_file() else ""

    page, _cache = render_tutorial(
        source_path.read_text(encoding="utf-8"),
        source_path.parent,
        read_symbols(previous),
        source_path.name,
        retrace=retrace,
    )

    return page


def build_tutorial(source_path, output_path=None, retrace=False):
    """Build ``source_path`` and write the page; return the page path."""
    source_path = Path(source_path)
    output_path = Path(output_path) if output_path else default_output_path(source_path)
    page = _render_file(source_path, output_path, retrace=retrace)
    output_path.write_text(page, encoding="utf-8", newline="\n")
    size = len(page.encode("utf-8"))

    if size > SIZE_BUDGET_BYTES:
        logger.warning(f"{output_path} is {size} bytes, over the {SIZE_BUDGET_BYTES}")

    logger.info(f"Built {output_path} ({size} bytes)")

    return output_path


def is_up_to_date(source_path, output_path=None):
    """Return True when rebuilding ``source_path`` reproduces its output."""
    source_path = Path(source_path)
    output_path = Path(output_path) if output_path else default_output_path(source_path)
    page = _render_file(source_path, output_path)
    committed = output_path.read_text(encoding="utf-8").replace("\r\n", "\n")

    return page == committed


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("source", type=Path, help="the <slug>.src.html page")
    parser.add_argument("output", type=Path, nargs="?", help="default: <slug>.html")
    parser.add_argument("--retrace", action="store_true", help="re-trace all glyphs")
    parser.add_argument(
        "--check", action="store_true", help="fail if the built file is stale"
    )
    args = parser.parse_args(argv)

    if args.check:
        if not is_up_to_date(args.source, args.output):
            logger.error(f"{args.source} has changed since it was last built")

            return 1

        return 0

    build_tutorial(args.source, args.output, retrace=args.retrace)

    return 0


if __name__ == "__main__":
    sys.exit(main())
