from microdrop_style.colors import PRIMARY_SHADE, SECONDARY_SHADE, WHITE, PRIMARY_COLOR, WARNING_COLOR

NUMBER_OF_CHANNELS = 120

ELECTRODE_ON =  SECONDARY_SHADE[600]
ELECTRODE_OFF = SECONDARY_SHADE[900]
ELECTRODE_NO_CHANNEL = WARNING_COLOR
ELECTRODE_LINE = SECONDARY_SHADE[400]
ELECTRODE_TEXT_COLOR = WHITE
ELECTRODE_CHANNEL_EDITING = "teal"

CONNECTION_LINE_OFF = WHITE
CONNECTION_LINE_ON_DEFAULT = PRIMARY_COLOR

ROUTE_SELECTED = "yellow"
ROUTE_CW_LOOP = "red"
ROUTE_CCW_LOOP = "orange"
ROUTE_COLOR_POOL = (PRIMARY_SHADE[300], PRIMARY_SHADE[400], PRIMARY_SHADE[500], PRIMARY_SHADE[600])
AUTOROUTE_COLOR = "pink"

default_alphas = {'connection': 1.0, 'fill': 0.5, 'text': 1.0}