# AUTO-GENERATED by tools/gen_proxy.py — DO NOT EDIT
# Generated: 2026-04-09T00:37:16
# MCU schema: /Users/alex/Downloads/Dropletbot-canada/firmware/MCU/commands.yaml
# DRV schema: /Users/alex/Downloads/Dropletbot-canada/firmware/MotorDriver/commands.yaml
#
# This file provides typed proxy classes for the DropletBot firmware.
# Import and use: from proxy import SignalBoardProxy, MotorBoardProxy

from __future__ import annotations
import struct
import time
from typing import NamedTuple, TYPE_CHECKING

if TYPE_CHECKING:
    from .portable_dropbot_service import DropletBotUart


# ============================================================
# Protocol Constants
# ============================================================
class Frame:
    HEAD = 0x7CF1
    HEAD0 = HEAD >> 8
    HEAD1 = HEAD & 0xFF
    HEAD_SIZE = 11
    ACK_OK = 0x00
    ACK_FAIL = 0x01
    REQ = 0xFF
    RESP_OK = 0xF0
    RESP_FAIL = 0xF1
    RESP_BUSY = 0xF2
    RESP_ERR = 0xF3
    RESP_UNKNOWN = 0xF4
    RESP_TIMEOUT = 0xF5

    @staticmethod
    def to_str(ftype: int) -> str:
        return {
            Frame.REQ: 'REQUEST', Frame.ACK_OK: 'ACK OK', Frame.ACK_FAIL: 'ACK FAIL',
            Frame.RESP_OK: 'SUCCESS', Frame.RESP_FAIL: 'FAIL', Frame.RESP_BUSY: 'BUSY',
            Frame.RESP_ERR: 'CMD ERROR', Frame.RESP_UNKNOWN: 'UNKNOWN CMD',
            Frame.RESP_TIMEOUT: 'TIMEOUT',
        }.get(ftype, f'UNKNOWN(0x{ftype:02X})')


# ============================================================
# SignalBoard (head=0x12)
# ============================================================

class SignalBoardCmd:
    """Command IDs for SignalBoard."""
    HEAD = 0x12
    RESET = 0x1200  # MCU software reset
    LOGIN = 0x1201  # Handshake login with timestamp
    VERSION = 0x1202  # Get firmware version
    HW_RESET = 0x1203  # Hardware reset self-check
    STATUS = 0x1204  # Query system status — returns 17 x uint16 fields
    TEMP_SET_TARGET = 0x1210  # Set heater target temperature
    TEMP_START_STOP = 0x1211  # Enable/disable heater control
    TEMP_READ_INFO = 0x1212  # Read current temperature info
    TEMP_READ_PARAMS = 0x1213  # Read PID parameters
    TEMP_SET_PARAMS = 0x1214  # Set PID parameters
    RGB_LIGHT_CTRL = 0x1221  # Set RGB indicator LED
    ILLUMINATION_CTRL = 0x1222  # Set illumination LED brightness
    FLUORESCENCE_CTRL = 0x1223  # Set fluorescence LED brightness (1 byte: 0-255, 2 bytes: 0-65535)
    ELECTRODE_SET_VOLT = 0x1224  # Set HV electrode voltage
    ELECTRODE_STATE = 0x1225  # Set electrode channel states (120 channels as 16 bytes)
    ELECTRODE_SET_FREQ = 0x1226  # Set electrode actuation frequency
    PMT_ACQUIRE_START = 0x1227  # Start PMT ADC sampling
    PMT_DATA_REPORT = 0x1228  # PMT data upload (device → host)
    PMT_GAIN_SET = 0x1229  # Set PMT gain
    PMT_STATUS_REPORT = 0x122A  # PMT heartbeat/status
    PMT_POWER = 0x122B  # PMT power control
    PMT_START_DEBUG = 0x122C  # Start PMT debug sampling
    PMT_STOP_DEBUG = 0x122D  # Stop PMT debug sampling
    PMT_DATA_UPLOAD_DEBUG = 0x122E  # Upload buffered PMT debug samples
    CAP_SHORT_DETECT = 0x1230  # Capacitor short circuit detection
    MEASURE_CAPACITANCE = 0x122F  # On-demand capacitance measurement of active electrodes
    CHANNEL_CAPACITANCES = 0x1235  # Per-channel capacitance measurement without altering HV/frequency
    RAW_ADC_CAP = 0x1236  # Raw ADC samples from capacitance feedback for waveform analysis
    CAP_CALIBRATE_BIAS = 0x1237  # Calibrate capacitance DC bias (reference voltage)
    SET_BOOT_5V_DELAY = 0x1238  # Set 5V boot delay in EasyFlash
    CAP_AUTORANGE = 0x1239  # Configure capacitance autorange
    READ_VREF = 0x123A  # Read voltage divider reference (PC4, ADC12_IN14)
    SPI_ADC_DIAG = 0x123B  # SPI ADC diagnostic — bus connectivity test, detected type, raw values
    CAP_SET_MODE = 0x123C  # Set/get capacitance measurement mode (IQR or VREF threshold)
    CAP_CROSS_CAL = 0x123D  # Cross-calibrate BACK1/BACK2 C_fb using active electrodes measured by BACK3
    CAP_CALIBRATE = 0x1231  # Capacitance calibration — returns calibrated C_fb + raw IQR matrix
    CAP_READ_ALL = 0x1232  # Read capacitance on all 120 channels
    HV_TEST = 0x1233  # Test HV at 5 voltage levels
    LOADED_SHORT_DETECT = 0x12AC  # Chip presence and short circuit detection
    SHORT_CIRCUIT_DETECT = 0x12AD  # Full 120-channel short circuit scan
    SET_PARAMS = 0x1260  # Write parameter to flash
    GET_PARAMS = 0x1261  # Read parameter from flash
    PRESET_PARAMS = 0x1262  # Save all parameters to flash
    SET_ALARM_LEVEL = 0x1273  # Set alarm reporting level
    REPORT_ALARM = 0x1272  # Alarm report (device → host)
    CLEAR_ALARM = 0x1274  # Clear/confirm alarm by code
    SET_LOG_LEVEL = 0x1271  # Set log reporting level
    REPORT_LOG = 0x1270  # Log report (device → host)
    SET_REPORT_CYCLE = 0x12F6  # Set event streaming mask
    SET_REPORT_CYCLE2 = 0x12F7  # Set event streaming interval
    FW_PREPARE = 0x1280  # Firmware upgrade handshake
    FW_TRANSFER = 0x1281  # Firmware data transfer
    FW_RESULT = 0x1282  # Firmware upgrade result
    READ_TEMP_SENSORS = 0x12A0  # Read all 5 temperature sensors
    TEMP_HEAT_PWM = 0x12A1  # Set heater PWM duty directly (debug)
    BUZZER_CTRL = 0x12A2  # Control buzzer
    FAN_CTRL = 0x12A3  # Control MCU board fan
    POWER_CTRL = 0x12A4  # Control system power pin
    READ_ADC_DATA = 0x12A5  # Read 8-channel ADC
    CAP_MATCH = 0x12A6  # Set capacitance matching switches
    HV_PWM_FREQ = 0x12A7  # Set HV PWM frequency
    HV_VALUE = 0x12A8  # Set HV voltage value
    DDS_POT = 0x12A9  # Control DDS digital potentiometer
    DDS_WAVE = 0x12AA  # Configure DDS waveform
    DAC_SET_VOLT = 0x12AB  # Set DAC output voltage

    EVT_STATUS = 1
    EVT_TEMPERATURE = 2
    EVT_HV_VOLTAGE = 4
    EVT_CHIP_DETECT = 8
    EVT_SHORT_CIRCUIT = 16
    EVT_CAPACITANCE = 32
    EVT_ALL = 65535

    PARAMS = {
        "product_model": "_dp_model",
        "heater": "g_temp_params",
    }


class SignalBoardAlarms:
    """Alarm codes for SignalBoard."""
    TEMP_SENSOR_COMM_PARTIAL = "05001"  # Temperature sensor partial channel communication fault
    TEMP_SENSOR_READ_PARTIAL = "05002"  # Temperature sensor partial channel reading fault
    TEMP_SENSOR_FAULT = "05003"  # Temperature sensor fault
    HUMIDITY_SENSOR_COMM = "05004"  # Humidity sensor communication fault
    TEMP_CTRL_OVERLIMIT = "09001"  # Heater temperature over-limit
    TEMP_CTRL_NO_HEAT = "09002"  # Heater not raising temperature
    ADC_DETECT_FAULT = "07001"  # ADC detection fault
    CHIP_DETECT_FAULT = "07002"  # Chip presence detection fault
    SHORT_CIRCUIT_DETECT_FAULT = "07003"  # Short-circuit detection fault
    HV_CAP_CAL_FAULT = "01001"  # HV capacitance calibration fault
    HV_CHAN_DETECT_WARN = "01002"  # HV channel detect fault (non-critical)
    HV_CHAN_DETECT_SEV = "01003"  # HV channel detect fault (critical)
    HV_INACCURATE = "01004"  # HV voltage inaccurate
    CAP_FEEDBACK_SATURATED = "01005"  # Capacitance feedback saturated
    HV_VOLTAGE_DEVIATION = "01006"  # HV voltage deviates >20% from setpoint

    @staticmethod
    def to_str(code: str) -> str:
        _map = {
            "05001": "Temperature sensor partial channel communication fault",
            "05002": "Temperature sensor partial channel reading fault",
            "05003": "Temperature sensor fault",
            "05004": "Humidity sensor communication fault",
            "09001": "Heater temperature over-limit",
            "09002": "Heater not raising temperature",
            "07001": "ADC detection fault",
            "07002": "Chip presence detection fault",
            "07003": "Short-circuit detection fault",
            "01001": "HV capacitance calibration fault",
            "01002": "HV channel detect fault (non-critical)",
            "01003": "HV channel detect fault (critical)",
            "01004": "HV voltage inaccurate",
            "01005": "Capacitance feedback saturated",
            "01006": "HV voltage deviates >20% from setpoint",
        }
        return _map.get(code, f"Unknown alarm: {code}")


class SignalBoardLOGINResponse(NamedTuple):
    status: int  # 0=success

class SignalBoardVERSIONResponse(NamedTuple):
    version_string: str  # module;hw_version;sw_version

class SignalBoardSTATUSResponse(NamedTuple):
    cur_temp: float  # °C
    target_temp: float  # °C
    out_power: int  # %
    rgy_state: int  # 0=off, 1=red, 2=green, 3=yellow
    light_led_bright: int  # %
    flu_led_bright: int  # ‰
    chip_on_pad: int  # 0=absent, 1=present
    chip_cap: int  # pF
    chip_short_circuit: int  # 0=ok, 1=short
    chip_res: int
    dev_temp: float  # °C
    dev_hum: float  # %RH
    fan_duty: int  # %
    pmt: int
    hv_vol: float  # V
    hv_freq: int  # Hz
    cap_match: int

class SignalBoardTEMP_READ_INFOResponse(NamedTuple):
    channel: int
    current: float  # °C
    target: float  # °C
    output: float  # %

class SignalBoardTEMP_READ_PARAMSResponse(NamedTuple):
    channel: int
    kp: float
    ki: float
    kd: float
    period_ms: int

class SignalBoardPMT_ACQUIRE_STARTResponse(NamedTuple):
    packet_count: int

class SignalBoardPMT_POWERResponse(NamedTuple):
    power_state: int  # 0=off, 1=on

class SignalBoardPMT_START_DEBUGResponse(NamedTuple):
    sample_limit: int

class SignalBoardPMT_DATA_UPLOAD_DEBUGResponse(NamedTuple):
    packet_count: int

class SignalBoardCAP_SHORT_DETECTResponse(NamedTuple):
    short_detected: int  # 0=ok, 1=short

class SignalBoardMEASURE_CAPACITANCEResponse(NamedTuple):
    capacitance_pf: float  # Capacitance in pF (float, range 0-100000)
    cal_proportion: float  # Calibration factor (amplitude per pF)
    mode: int  # 0=IQR, 1=VREF
    n_total: int  # ADC samples per iteration (averaged across n_averages)
    n_high: int  # High-side samples per iteration
    n_low: int  # Low-side samples per iteration
    n_dropped: int  # Dropped samples per iteration
    elapsed_us: int  # Total measurement time in microseconds (all averages)

class SignalBoardCHANNEL_CAPACITANCESResponse(NamedTuple):
    results: bytes  # First byte=count, then count x float32 BE (pF per channel)

class SignalBoardRAW_ADC_CAPResponse(NamedTuple):
    samples: bytes  # uint16[n] big-endian ADC values (12-bit, 0-4095)

class SignalBoardCAP_CALIBRATE_BIASResponse(NamedTuple):
    bias_adc: float  # Bias in ADC units (0-4095)
    bias_volts: float  # Bias in volts

class SignalBoardSET_BOOT_5V_DELAYResponse(NamedTuple):
    delay_ms: int  # Stored value

class SignalBoardCAP_AUTORANGEResponse(NamedTuple):
    enable: int  # Echo enable
    max_pct: int  # Echo max_pct
    min_pct: int  # Echo min_pct

class SignalBoardREAD_VREFResponse(NamedTuple):
    voltage: float  # Expected ~1.65V

class SignalBoardSPI_ADC_DIAGResponse(NamedTuple):
    adc_type: int  # 0=none, 1=ADC128S052, 2=ADS7076
    bus_test: int  # Bit flags: b0=MISO has variation, b1=non-zero reading, b2=re-init OK
    ch0_raw: int  # Channel 0 raw 12/16-bit value
    ch1_raw: int  # Channel 1 raw
    ch2_raw: int  # Channel 2 raw
    ch3_raw: int  # Channel 3 raw
    ch4_raw: int  # Channel 4 raw
    ch5_raw: int  # Channel 5 raw
    ch6_raw: int  # Channel 6 raw
    ch7_raw: int  # Channel 7 raw
    ads706x_status: int  # ADS706x status register value from init (0xFF=sentinel)

class SignalBoardCAP_SET_MODEResponse(NamedTuple):
    mode: int  # Active mode after set
    vref_voltage: float  # Current V_ref reading from PC4

class SignalBoardCAP_CROSS_CALResponse(NamedTuple):
    cfb_new: float  # Calibrated C_fb in farads (0 on failure)
    cfb_back3: float  # BACK3 C_fb for reference

class SignalBoardCAP_CALIBRATEResponse(NamedTuple):
    cfb_back1: float  # Calibrated C_fb for BACK1 (1uF nominal) in farads
    cfb_back2: float  # Calibrated C_fb for BACK2 (470nF nominal) in farads
    cfb_back3: float  # Calibrated C_fb for BACK3 (100nF nominal) in farads
    iqr_b1_r10: int  # Raw IQR: BACK1 + REF 10pF
    iqr_b1_r100: int  # Raw IQR: BACK1 + REF 100pF
    iqr_b1_r470: int  # Raw IQR: BACK1 + REF 470pF
    iqr_b2_r10: int  # Raw IQR: BACK2 + REF 10pF
    iqr_b2_r100: int  # Raw IQR: BACK2 + REF 100pF
    iqr_b2_r470: int  # Raw IQR: BACK2 + REF 470pF
    iqr_b3_r10: int  # Raw IQR: BACK3 + REF 10pF
    iqr_b3_r100: int  # Raw IQR: BACK3 + REF 100pF
    iqr_b3_r470: int  # Raw IQR: BACK3 + REF 470pF

class SignalBoardCAP_READ_ALLResponse(NamedTuple):
    channels: bytes  # Per-channel capacitance values

class SignalBoardHV_TESTResponse(NamedTuple):
    actual_voltages: bytes

class SignalBoardLOADED_SHORT_DETECTResponse(NamedTuple):
    chip_loaded: int  # 0=absent, 1=present
    short_circuit: int  # 0=ok, 1=short

class SignalBoardSHORT_CIRCUIT_DETECTResponse(NamedTuple):
    channels: bytes

class SignalBoardGET_PARAMSResponse(NamedTuple):
    param_name: str
    value: bytes

class SignalBoardSET_REPORT_CYCLEResponse(NamedTuple):
    mask: int

class SignalBoardSET_REPORT_CYCLE2Response(NamedTuple):
    interval_ms: int

class SignalBoardFW_PREPAREResponse(NamedTuple):
    status: int
    result: int  # 0=ready, 1=erase failed

class SignalBoardFW_TRANSFERResponse(NamedTuple):
    status: int
    frame_index_h: int
    frame_index_l: int

class SignalBoardREAD_TEMP_SENSORSResponse(NamedTuple):
    temp_1: float  # °C
    temp_2: float  # °C
    temp_3: float  # °C
    temp_4: float  # °C
    temp_5: float  # °C

class SignalBoardREAD_ADC_DATAResponse(NamedTuple):
    ch0: float  # V
    ch1: float  # V
    ch2: float  # V
    ch3: float  # V
    ch4: float  # V
    ch5: float  # V
    ch6: float  # V
    ch7: float  # V

class SignalBoardHV_VALUEResponse(NamedTuple):
    actual_voltage: float  # V

class SignalBoardDDS_POTResponse(NamedTuple):
    value: int

class SignalBoardDAC_SET_VOLTResponse(NamedTuple):
    actual_voltage: float  # V

class SignalBoardProxy:
    """SignalBoard typed proxy — auto-generated from commands.yaml."""

    def __init__(self, transport: 'DropletBotUart'):
        self._transport = transport

    def reset(self) -> None:
        """MCU software reset"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1200, payload)
        self._transport._w(packet)
        return None

    def login(self, year: int, month: int, day: int, hour: int, minute: int, second: int) -> SignalBoardLOGINResponse | None:
        """Handshake login with timestamp"""
        payload = struct.pack('>BBBBBB', year, month, day, hour, minute, second)
        packet = self._transport._make_cmd_packet(0x1201, payload)
        resp = self._transport._wr(packet, 0x1201, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 1:
            return None
        raw = struct.unpack('>B', resp[:1])
        return SignalBoardLOGINResponse(status=raw[0])

    def version(self) -> SignalBoardVERSIONResponse | None:
        """Get firmware version"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1202, payload)
        resp = self._transport._wr(packet, 0x1202, timeout_s=2.0)
        if resp is None:
            return None
        return SignalBoardVERSIONResponse(version_string=resp.decode('utf-8'))

    def hw_reset(self) -> None:
        """Hardware reset self-check"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1203, payload)
        self._transport._w(packet)
        return None

    def status(self) -> SignalBoardSTATUSResponse | None:
        """Query system status — returns 17 x uint16 fields"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1204, payload)
        resp = self._transport._wr(packet, 0x1204, timeout_s=3.0)
        if resp is None:
            return None
        if len(resp) < 34:
            return None
        raw = struct.unpack('>HHHHHHHHHHHHHHHHH', resp[:34])
        return SignalBoardSTATUSResponse(cur_temp=raw[0] * 0.01, target_temp=raw[1] * 0.01, out_power=raw[2], rgy_state=raw[3], light_led_bright=raw[4], flu_led_bright=raw[5], chip_on_pad=raw[6], chip_cap=raw[7], chip_short_circuit=raw[8], chip_res=raw[9], dev_temp=raw[10] * 0.01, dev_hum=raw[11] * 0.01, fan_duty=raw[12], pmt=raw[13], hv_vol=raw[14] * 0.01, hv_freq=raw[15], cap_match=raw[16])

    def temp_set_target(self, target: float, channel: int = 0) -> bool:
        """Set heater target temperature"""
        payload = struct.pack('>Bh', channel, int(target / 0.01))
        packet = self._transport._make_cmd_packet(0x1210, payload)
        return self._transport._wr(packet, 0x1210, timeout_s=2.0) is not None

    def temp_start_stop(self, enable: int, channel: int = 0) -> bool:
        """Enable/disable heater control"""
        payload = struct.pack('>BB', channel, enable)
        packet = self._transport._make_cmd_packet(0x1211, payload)
        return self._transport._wr(packet, 0x1211, timeout_s=2.0) is not None

    def temp_read_info(self, channel: int = 0) -> SignalBoardTEMP_READ_INFOResponse | None:
        """Read current temperature info"""
        payload = struct.pack('>B', channel)
        packet = self._transport._make_cmd_packet(0x1212, payload)
        resp = self._transport._wr(packet, 0x1212, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 7:
            return None
        raw = struct.unpack('>Bhhh', resp[:7])
        return SignalBoardTEMP_READ_INFOResponse(channel=raw[0], current=raw[1] * 0.01, target=raw[2] * 0.01, output=raw[3] * 0.01)

    def temp_read_params(self, channel: int = 0) -> SignalBoardTEMP_READ_PARAMSResponse | None:
        """Read PID parameters"""
        payload = struct.pack('>B', channel)
        packet = self._transport._make_cmd_packet(0x1213, payload)
        resp = self._transport._wr(packet, 0x1213, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 9:
            return None
        raw = struct.unpack('>Bhhhh', resp[:9])
        return SignalBoardTEMP_READ_PARAMSResponse(channel=raw[0], kp=raw[1] * 0.01, ki=raw[2] * 0.01, kd=raw[3] * 0.01, period_ms=raw[4])

    def temp_set_params(self, kp: float, ki: float, kd: float, period_ms: int, channel: int = 0) -> bool:
        """Set PID parameters"""
        payload = struct.pack('>Bhhhh', channel, int(kp / 0.01), int(ki / 0.01), int(kd / 0.01), period_ms)
        packet = self._transport._make_cmd_packet(0x1214, payload)
        return self._transport._wr(packet, 0x1214, timeout_s=2.0) is not None

    def rgb_light_ctrl(self, color: int) -> bool:
        """Set RGB indicator LED"""
        payload = struct.pack('>B', color)
        packet = self._transport._make_cmd_packet(0x1221, payload)
        return self._transport._wr(packet, 0x1221, timeout_s=2.0) is not None

    def illumination_ctrl(self, brightness: int) -> bool:
        """Set illumination LED brightness"""
        payload = struct.pack('>B', brightness)
        packet = self._transport._make_cmd_packet(0x1222, payload)
        return self._transport._wr(packet, 0x1222, timeout_s=2.0) is not None

    def fluorescence_ctrl(self, brightness: int) -> bool:
        """Set fluorescence LED brightness (1 byte: 0-255, 2 bytes: 0-65535)"""
        payload = struct.pack('>H', brightness)
        packet = self._transport._make_cmd_packet(0x1223, payload)
        return self._transport._wr(packet, 0x1223, timeout_s=2.0) is not None

    def electrode_set_volt(self, amplitude: int) -> bool:
        """Set HV electrode voltage"""
        payload = struct.pack('>B', amplitude)
        packet = self._transport._make_cmd_packet(0x1224, payload)
        return self._transport._wr(packet, 0x1224, timeout_s=2.0) is not None

    def electrode_state(self, states: bytes) -> bool:
        """Set electrode channel states (120 channels as 16 bytes)"""
        payload = struct.pack('>16s', states)
        packet = self._transport._make_cmd_packet(0x1225, payload)
        return self._transport._wr(packet, 0x1225, timeout_s=2.0) is not None

    def electrode_set_freq(self, frequency: int) -> bool:
        """Set electrode actuation frequency"""
        payload = struct.pack('>H', frequency)
        packet = self._transport._make_cmd_packet(0x1226, payload)
        return self._transport._wr(packet, 0x1226, timeout_s=2.0) is not None

    def pmt_acquire_start(self) -> SignalBoardPMT_ACQUIRE_STARTResponse | None:
        """Start PMT ADC sampling"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1227, payload)
        resp = self._transport._wr(packet, 0x1227, timeout_s=10.0)
        if resp is None:
            return None
        if len(resp) < 2:
            return None
        raw = struct.unpack('<H', resp[:2])
        return SignalBoardPMT_ACQUIRE_STARTResponse(packet_count=raw[0])

    def pmt_gain_set(self, gain: int) -> bool:
        """Set PMT gain"""
        payload = struct.pack('>B', gain)
        packet = self._transport._make_cmd_packet(0x1229, payload)
        return self._transport._wr(packet, 0x1229, timeout_s=2.0) is not None

    def pmt_power(self, enable: int) -> SignalBoardPMT_POWERResponse | None:
        """PMT power control"""
        payload = struct.pack('>B', enable)
        packet = self._transport._make_cmd_packet(0x122B, payload)
        resp = self._transport._wr(packet, 0x122B, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 1:
            return None
        raw = struct.unpack('>B', resp[:1])
        return SignalBoardPMT_POWERResponse(power_state=raw[0])

    def pmt_start_debug(self, sample_limit: int) -> SignalBoardPMT_START_DEBUGResponse | None:
        """Start PMT debug sampling"""
        payload = struct.pack('<H', sample_limit)
        packet = self._transport._make_cmd_packet(0x122C, payload)
        resp = self._transport._wr(packet, 0x122C, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 2:
            return None
        raw = struct.unpack('<H', resp[:2])
        return SignalBoardPMT_START_DEBUGResponse(sample_limit=raw[0])

    def pmt_stop_debug(self) -> bool:
        """Stop PMT debug sampling"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x122D, payload)
        return self._transport._wr(packet, 0x122D, timeout_s=2.0) is not None

    def pmt_data_upload_debug(self) -> SignalBoardPMT_DATA_UPLOAD_DEBUGResponse | None:
        """Upload buffered PMT debug samples"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x122E, payload)
        resp = self._transport._wr(packet, 0x122E, timeout_s=10.0)
        if resp is None:
            return None
        if len(resp) < 2:
            return None
        raw = struct.unpack('<H', resp[:2])
        return SignalBoardPMT_DATA_UPLOAD_DEBUGResponse(packet_count=raw[0])

    def cap_short_detect(self) -> SignalBoardCAP_SHORT_DETECTResponse | None:
        """Capacitor short circuit detection"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1230, payload)
        resp = self._transport._wr(packet, 0x1230, timeout_s=5.0)
        if resp is None:
            return None
        if len(resp) < 1:
            return None
        raw = struct.unpack('>B', resp[:1])
        return SignalBoardCAP_SHORT_DETECTResponse(short_detected=raw[0])

    def measure_capacitance(self, n_averages: int = 1) -> SignalBoardMEASURE_CAPACITANCEResponse | None:
        """On-demand capacitance measurement of active electrodes"""
        payload = struct.pack('>H', n_averages)
        packet = self._transport._make_cmd_packet(0x122F, payload)
        resp = self._transport._wr(packet, 0x122F, timeout_s=5.0)
        if resp is None:
            return None
        if len(resp) < 21:
            return None
        raw = struct.unpack('>ffBHHHHI', resp[:21])
        return SignalBoardMEASURE_CAPACITANCEResponse(capacitance_pf=raw[0], cal_proportion=raw[1], mode=raw[2], n_total=raw[3], n_high=raw[4], n_low=raw[5], n_dropped=raw[6], elapsed_us=raw[7])

    def channel_capacitances(self, channels: bytes) -> SignalBoardCHANNEL_CAPACITANCESResponse | None:
        """Per-channel capacitance measurement without altering HV/frequency"""
        payload = b''
        payload += channels
        packet = self._transport._make_cmd_packet(0x1235, payload)
        resp = self._transport._wr(packet, 0x1235, timeout_s=60.0)
        if resp is None:
            return None
        return SignalBoardCHANNEL_CAPACITANCESResponse(results=resp)

    def raw_adc_cap(self, n_samples: int = 0) -> SignalBoardRAW_ADC_CAPResponse | None:
        """Raw ADC samples from capacitance feedback for waveform analysis"""
        payload = struct.pack('>H', n_samples)
        packet = self._transport._make_cmd_packet(0x1236, payload)
        resp = self._transport._wr(packet, 0x1236, timeout_s=5.0)
        if resp is None:
            return None
        return SignalBoardRAW_ADC_CAPResponse(samples=resp)

    def cap_calibrate_bias(self) -> SignalBoardCAP_CALIBRATE_BIASResponse | None:
        """Calibrate capacitance DC bias (reference voltage)"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1237, payload)
        resp = self._transport._wr(packet, 0x1237, timeout_s=5.0)
        if resp is None:
            return None
        if len(resp) < 8:
            return None
        raw = struct.unpack('>ff', resp[:8])
        return SignalBoardCAP_CALIBRATE_BIASResponse(bias_adc=raw[0], bias_volts=raw[1])

    def set_boot_5v_delay(self, delay_ms: int) -> SignalBoardSET_BOOT_5V_DELAYResponse | None:
        """Set 5V boot delay in EasyFlash"""
        payload = struct.pack('>I', delay_ms)
        packet = self._transport._make_cmd_packet(0x1238, payload)
        resp = self._transport._wr(packet, 0x1238, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 4:
            return None
        raw = struct.unpack('>I', resp[:4])
        return SignalBoardSET_BOOT_5V_DELAYResponse(delay_ms=raw[0])

    def cap_autorange(self, enable: int, max_pct: int, min_pct: int) -> SignalBoardCAP_AUTORANGEResponse | None:
        """Configure capacitance autorange"""
        payload = struct.pack('>BBB', enable, max_pct, min_pct)
        packet = self._transport._make_cmd_packet(0x1239, payload)
        resp = self._transport._wr(packet, 0x1239, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 3:
            return None
        raw = struct.unpack('>BBB', resp[:3])
        return SignalBoardCAP_AUTORANGEResponse(enable=raw[0], max_pct=raw[1], min_pct=raw[2])

    def read_vref(self) -> SignalBoardREAD_VREFResponse | None:
        """Read voltage divider reference (PC4, ADC12_IN14)"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x123A, payload)
        resp = self._transport._wr(packet, 0x123A, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 4:
            return None
        raw = struct.unpack('>f', resp[:4])
        return SignalBoardREAD_VREFResponse(voltage=raw[0])

    def spi_adc_diag(self) -> SignalBoardSPI_ADC_DIAGResponse | None:
        """SPI ADC diagnostic — bus connectivity test, detected type, raw values"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x123B, payload)
        resp = self._transport._wr(packet, 0x123B, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 19:
            return None
        raw = struct.unpack('>BBHHHHHHHHB', resp[:19])
        return SignalBoardSPI_ADC_DIAGResponse(adc_type=raw[0], bus_test=raw[1], ch0_raw=raw[2], ch1_raw=raw[3], ch2_raw=raw[4], ch3_raw=raw[5], ch4_raw=raw[6], ch5_raw=raw[7], ch6_raw=raw[8], ch7_raw=raw[9], ads706x_status=raw[10])

    def cap_set_mode(self, mode: int) -> SignalBoardCAP_SET_MODEResponse | None:
        """Set/get capacitance measurement mode (IQR or VREF threshold)"""
        payload = struct.pack('>B', mode)
        packet = self._transport._make_cmd_packet(0x123C, payload)
        resp = self._transport._wr(packet, 0x123C, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 5:
            return None
        raw = struct.unpack('>Bf', resp[:5])
        return SignalBoardCAP_SET_MODEResponse(mode=raw[0], vref_voltage=raw[1])

    def cap_cross_cal(self, target_fbc: int, n_averages: int = 10) -> SignalBoardCAP_CROSS_CALResponse | None:
        """Cross-calibrate BACK1/BACK2 C_fb using active electrodes measured by BACK3"""
        payload = struct.pack('>BH', target_fbc, n_averages)
        packet = self._transport._make_cmd_packet(0x123D, payload)
        resp = self._transport._wr(packet, 0x123D, timeout_s=30.0)
        if resp is None:
            return None
        if len(resp) < 8:
            return None
        raw = struct.unpack('>ff', resp[:8])
        return SignalBoardCAP_CROSS_CALResponse(cfb_new=raw[0], cfb_back3=raw[1])

    def cap_calibrate(self) -> SignalBoardCAP_CALIBRATEResponse | None:
        """Capacitance calibration — returns calibrated C_fb + raw IQR matrix"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1231, payload)
        resp = self._transport._wr(packet, 0x1231, timeout_s=30.0)
        if resp is None:
            return None
        if len(resp) < 30:
            return None
        raw = struct.unpack('>fffHHHHHHHHH', resp[:30])
        return SignalBoardCAP_CALIBRATEResponse(cfb_back1=raw[0], cfb_back2=raw[1], cfb_back3=raw[2], iqr_b1_r10=raw[3], iqr_b1_r100=raw[4], iqr_b1_r470=raw[5], iqr_b2_r10=raw[6], iqr_b2_r100=raw[7], iqr_b2_r470=raw[8], iqr_b3_r10=raw[9], iqr_b3_r100=raw[10], iqr_b3_r470=raw[11])

    def cap_read_all(self, switch_time_ms: int = 20) -> SignalBoardCAP_READ_ALLResponse | None:
        """Read capacitance on all 120 channels"""
        payload = struct.pack('>H', switch_time_ms)
        packet = self._transport._make_cmd_packet(0x1232, payload)
        resp = self._transport._wr(packet, 0x1232, timeout_s=60.0)
        if resp is None:
            return None
        return SignalBoardCAP_READ_ALLResponse(channels=resp[:120])

    def hv_test(self, voltages: bytes = b"\x28\x50\x78\xa0\xc8") -> SignalBoardHV_TESTResponse | None:
        """Test HV at 5 voltage levels"""
        payload = struct.pack('>5s', bytes(voltages) if isinstance(voltages, list) else voltages)
        packet = self._transport._make_cmd_packet(0x1233, payload)
        resp = self._transport._wr(packet, 0x1233, timeout_s=15.0)
        if resp is None:
            return None
        return SignalBoardHV_TESTResponse(actual_voltages=resp[:5])

    def loaded_short_detect(self) -> SignalBoardLOADED_SHORT_DETECTResponse | None:
        """Chip presence and short circuit detection"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x12AC, payload)
        resp = self._transport._wr(packet, 0x12AC, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 2:
            return None
        raw = struct.unpack('>BB', resp[:2])
        return SignalBoardLOADED_SHORT_DETECTResponse(chip_loaded=raw[0], short_circuit=raw[1])

    def short_circuit_detect(self) -> SignalBoardSHORT_CIRCUIT_DETECTResponse | None:
        """Full 120-channel short circuit scan"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x12AD, payload)
        resp = self._transport._wr(packet, 0x12AD, timeout_s=30.0)
        if resp is None:
            return None
        return SignalBoardSHORT_CIRCUIT_DETECTResponse(channels=resp[:120])

    def set_params(self, param_name: str, value: bytes) -> bool:
        """Write parameter to flash"""
        payload = param_name.encode('utf-8') + b'\x00'
        payload += value
        packet = self._transport._make_cmd_packet(0x1260, payload)
        return self._transport._wr(packet, 0x1260, timeout_s=3.0) is not None

    def get_params(self, param_name: str) -> SignalBoardGET_PARAMSResponse | None:
        """Read parameter from flash"""
        payload = param_name.encode('utf-8') + b'\x00'
        packet = self._transport._make_cmd_packet(0x1261, payload)
        resp = self._transport._wr(packet, 0x1261, timeout_s=5.0)
        if resp is None:
            return None
        parts = resp.split(b'\x00', 1)
        if len(parts) == 2:
            return SignalBoardGET_PARAMSResponse(param_name=parts[0].decode('utf-8'), value=parts[1])
        return None

    def preset_params(self) -> bool:
        """Save all parameters to flash"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1262, payload)
        return self._transport._wr(packet, 0x1262, timeout_s=5.0) is not None

    def set_alarm_level(self, level: int) -> bool:
        """Set alarm reporting level"""
        payload = struct.pack('>B', level)
        packet = self._transport._make_cmd_packet(0x1273, payload)
        return self._transport._wr(packet, 0x1273, timeout_s=2.0) is not None

    def clear_alarm(self, alarm_code: bytes) -> bool:
        """Clear/confirm alarm by code"""
        payload = struct.pack('>5s', alarm_code)
        packet = self._transport._make_cmd_packet(0x1274, payload)
        return self._transport._wr(packet, 0x1274, timeout_s=2.0) is not None

    def set_log_level(self, level: int) -> bool:
        """Set log reporting level"""
        payload = struct.pack('>B', level)
        packet = self._transport._make_cmd_packet(0x1271, payload)
        return self._transport._wr(packet, 0x1271, timeout_s=2.0) is not None

    def set_report_cycle(self, mask: int) -> SignalBoardSET_REPORT_CYCLEResponse | None:
        """Set event streaming mask"""
        payload = struct.pack('>I', mask)
        packet = self._transport._make_cmd_packet(0x12F6, payload)
        resp = self._transport._wr(packet, 0x12F6, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 4:
            return None
        raw = struct.unpack('>I', resp[:4])
        return SignalBoardSET_REPORT_CYCLEResponse(mask=raw[0])

    def set_report_cycle2(self, interval_ms: int) -> SignalBoardSET_REPORT_CYCLE2Response | None:
        """Set event streaming interval"""
        payload = struct.pack('>I', interval_ms)
        packet = self._transport._make_cmd_packet(0x12F7, payload)
        resp = self._transport._wr(packet, 0x12F7, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 4:
            return None
        raw = struct.unpack('>I', resp[:4])
        return SignalBoardSET_REPORT_CYCLE2Response(interval_ms=raw[0])

    def fw_prepare(self, module_id: int = 0, upgrade_type: int = 1) -> SignalBoardFW_PREPAREResponse | None:
        """Firmware upgrade handshake"""
        payload = struct.pack('>BB', module_id, upgrade_type)
        packet = self._transport._make_cmd_packet(0x1280, payload)
        resp = self._transport._wr(packet, 0x1280, timeout_s=60.0)
        if resp is None:
            return None
        if len(resp) < 2:
            return None
        raw = struct.unpack('>BB', resp[:2])
        return SignalBoardFW_PREPAREResponse(status=raw[0], result=raw[1])

    def fw_transfer(self, module_id: int, total_frames: int, frame_index: int, data: bytes) -> SignalBoardFW_TRANSFERResponse | None:
        """Firmware data transfer"""
        payload = struct.pack('>BHH', module_id, total_frames, frame_index)
        payload += data
        packet = self._transport._make_cmd_packet(0x1281, payload)
        resp = self._transport._wr(packet, 0x1281, timeout_s=30.0)
        if resp is None:
            return None
        if len(resp) < 3:
            return None
        raw = struct.unpack('>BBB', resp[:3])
        return SignalBoardFW_TRANSFERResponse(status=raw[0], frame_index_h=raw[1], frame_index_l=raw[2])

    def read_temp_sensors(self) -> SignalBoardREAD_TEMP_SENSORSResponse | None:
        """Read all 5 temperature sensors"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x12A0, payload)
        resp = self._transport._wr(packet, 0x12A0, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 10:
            return None
        raw = struct.unpack('>hhhhh', resp[:10])
        return SignalBoardREAD_TEMP_SENSORSResponse(temp_1=raw[0] * 0.01, temp_2=raw[1] * 0.01, temp_3=raw[2] * 0.01, temp_4=raw[3] * 0.01, temp_5=raw[4] * 0.01)

    def temp_heat_pwm(self, duty1: int, duty2: int) -> bool:
        """Set heater PWM duty directly (debug)"""
        payload = struct.pack('>BB', duty1, duty2)
        packet = self._transport._make_cmd_packet(0x12A1, payload)
        return self._transport._wr(packet, 0x12A1, timeout_s=2.0) is not None

    def buzzer_ctrl(self, enable: int) -> bool:
        """Control buzzer"""
        payload = struct.pack('>B', enable)
        packet = self._transport._make_cmd_packet(0x12A2, payload)
        return self._transport._wr(packet, 0x12A2, timeout_s=2.0) is not None

    def fan_ctrl(self, enable: int) -> bool:
        """Control MCU board fan"""
        payload = struct.pack('>B', enable)
        packet = self._transport._make_cmd_packet(0x12A3, payload)
        return self._transport._wr(packet, 0x12A3, timeout_s=2.0) is not None

    def power_ctrl(self, enable: int) -> bool:
        """Control system power pin"""
        payload = struct.pack('>B', enable)
        packet = self._transport._make_cmd_packet(0x12A4, payload)
        return self._transport._wr(packet, 0x12A4, timeout_s=2.0) is not None

    def read_adc_data(self) -> SignalBoardREAD_ADC_DATAResponse | None:
        """Read 8-channel ADC"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x12A5, payload)
        resp = self._transport._wr(packet, 0x12A5, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 16:
            return None
        raw = struct.unpack('>HHHHHHHH', resp[:16])
        return SignalBoardREAD_ADC_DATAResponse(ch0=raw[0] * 0.01, ch1=raw[1] * 0.01, ch2=raw[2] * 0.01, ch3=raw[3] * 0.01, ch4=raw[4] * 0.01, ch5=raw[5] * 0.01, ch6=raw[6] * 0.01, ch7=raw[7] * 0.01)

    def cap_match(self, cap_470pf: int, cap_100pf: int, cap_10pf: int, gain: int) -> bool:
        """Set capacitance matching switches"""
        payload = struct.pack('>BBBB', cap_470pf, cap_100pf, cap_10pf, gain)
        packet = self._transport._make_cmd_packet(0x12A6, payload)
        return self._transport._wr(packet, 0x12A6, timeout_s=2.0) is not None

    def hv_pwm_freq(self, frequency: int) -> bool:
        """Set HV PWM frequency"""
        payload = struct.pack('>I', frequency)
        packet = self._transport._make_cmd_packet(0x12A7, payload)
        return self._transport._wr(packet, 0x12A7, timeout_s=2.0) is not None

    def hv_value(self, voltage: float) -> SignalBoardHV_VALUEResponse | None:
        """Set HV voltage value"""
        payload = struct.pack('>H', int(voltage / 0.01))
        packet = self._transport._make_cmd_packet(0x12A8, payload)
        resp = self._transport._wr(packet, 0x12A8, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 2:
            return None
        raw = struct.unpack('>H', resp[:2])
        return SignalBoardHV_VALUEResponse(actual_voltage=raw[0] * 0.01)

    def dds_pot(self, action: int, value: int) -> SignalBoardDDS_POTResponse | None:
        """Control DDS digital potentiometer"""
        payload = struct.pack('>BH', action, value)
        packet = self._transport._make_cmd_packet(0x12A9, payload)
        resp = self._transport._wr(packet, 0x12A9, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 2:
            return None
        raw = struct.unpack('>H', resp[:2])
        return SignalBoardDDS_POTResponse(value=raw[0])

    def dds_wave(self, waveform: int, frequency: int) -> bool:
        """Configure DDS waveform"""
        payload = struct.pack('>BI', waveform, frequency)
        packet = self._transport._make_cmd_packet(0x12AA, payload)
        return self._transport._wr(packet, 0x12AA, timeout_s=2.0) is not None

    def dac_set_volt(self, voltage: float) -> SignalBoardDAC_SET_VOLTResponse | None:
        """Set DAC output voltage"""
        payload = struct.pack('>H', int(voltage / 0.01))
        packet = self._transport._make_cmd_packet(0x12AB, payload)
        resp = self._transport._wr(packet, 0x12AB, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 2:
            return None
        raw = struct.unpack('>H', resp[:2])
        return SignalBoardDAC_SET_VOLTResponse(actual_voltage=raw[0] * 0.01)

# ============================================================
# MotorBoard (head=0x11)
# ============================================================

class MotorBoardCmd:
    """Command IDs for MotorBoard."""
    HEAD = 0x11
    RESET = 0x1100  # MCU software reset
    LOGIN = 0x1101  # Handshake login with timestamp
    VERSION = 0x1102  # Get firmware version
    HW_RESET = 0x1103  # Hardware reset self-check
    STATUS = 0x1104  # Query motor board status
    CHIP_CABIN_CTRL = 0x1120  # Control chip tray position
    CHIP_CABIN_READ = 0x1121  # Read chip tray position
    MAG_CTRL = 0x1122  # Control magnet position
    MAG_READ = 0x1123  # Read magnet position
    PUSHPAD_CTRL = 0x1124  # Control pogo pin plates
    PUSHPAD_READ = 0x1125  # Read pogo plate position
    FLUORESCENCE_CTRL = 0x1126  # Set fluorescence filter position
    FLUORESCENCE_READ = 0x1127  # Read fluorescence filter position
    PMT_CTRL = 0x1128  # Move PMT to position
    PMT_READ = 0x1129  # Query PMT position
    POWER_CTRL = 0x112A  # Motor board power control
    FAN_CTRL = 0x112B  # Motor board fan control
    CABIN_MAG_RESET = 0x1130  # Home chip tray and magnet axes
    PMT_RESET = 0x1131  # Home PMT motor
    FLU_RESET = 0x1132  # Home fluorescence filter
    PUSHPAD_RESET = 0x1133  # Home pogo pin plates
    PMT_MT_CTRL = 0x1140  # PMT motor control (routed from signal board)
    PMT_MT_SPEED_SET = 0x1141  # Set PMT motor speed
    MOTOR_CONTROL = 0x11B0  # Motor control — move, stop, home
    MOTOR_SPEED_SET = 0x11B1  # Set motor speed
    MOTOR_POSITION_QUERY = 0x11B3  # Query motor position
    MOTOR_OPTO_QUERY = 0x11B4  # Query all motor opto-coupler sensors
    SET_PARAMS = 0x1160  # Write parameter
    GET_PARAMS = 0x1161  # Read parameter
    PRESET_PARAMS = 0x1162  # Save all parameters to flash
    SET_ALARM_LEVEL = 0x1173  # Set alarm reporting level
    REPORT_ALARM = 0x1172  # Alarm report (device → host)
    CLEAR_ALARM = 0x1174  # Clear/confirm alarm by code
    SET_LOG_LEVEL = 0x1171  # Set log reporting level
    REPORT_LOG = 0x1170  # Log report (device → host)
    FW_PREPARE = 0x1180  # Firmware upgrade handshake
    FW_TRANSFER = 0x1181  # Firmware data transfer
    FW_RESULT = 0x1282  # Firmware upgrade result

    MOTOR_ACTION_ABSOLUTE = 0
    MOTOR_ACTION_RELATIVE = 1
    MOTOR_ACTION_STOP = 3
    MOTOR_ACTION_HOME = 4

    PARAMS = {
        "filter_defaults": "_dp_flu",
        "tray_defaults": "_dp_chip",
        "magnet_defaults": "_dp_magnet",
        "pmt_defaults": "_dp_pmt",
        "pogo_defaults": "_dp_pushpad",
        "product_model": "_dp_model",
        "tray_motor": "_mt_cabin_dp",
        "pmt_motor": "_mt_y_dp",
        "magnet_motor": "_mt_z_dp",
        "filter_motor": "_mt_flu_dp",
        "pogo_motor_left": "_mt_padl_dp",
        "pogo_motor_right": "_mt_padr_dp",
    }


class MotorBoardAlarms:
    """Alarm codes for MotorBoard."""
    CHIP_CABIN_MOTOR_FAULT = "04001"  # Chip tray motor fault
    PMT_MOTOR_FAULT = "04013"  # PMT motor fault
    MAG_Z_MOTOR_FAULT = "04025"  # Magnet Z motor fault
    FLU_MOTOR_FAULT = "04037"  # Fluorescence filter motor fault
    PUSHPAD_R_MOTOR_FAULT = "04049"  # Right pogo plate motor fault
    PUSHPAD_L_MOTOR_FAULT = "04061"  # Left pogo plate motor fault
    MAG_NOT_DISENGAGED = "04073"  # Magnet not in disengaged position
    CABIN_UNKNOWN_POS = "04074"  # Chip tray position unknown
    MAG_UNKNOWN_POS = "04075"  # Magnet position unknown
    PUSHPAD_FAULT = "04077"  # Pogo plate mechanism fault

    @staticmethod
    def to_str(code: str) -> str:
        _map = {
            "04001": "Chip tray motor fault",
            "04013": "PMT motor fault",
            "04025": "Magnet Z motor fault",
            "04037": "Fluorescence filter motor fault",
            "04049": "Right pogo plate motor fault",
            "04061": "Left pogo plate motor fault",
            "04073": "Magnet not in disengaged position",
            "04074": "Chip tray position unknown",
            "04075": "Magnet position unknown",
            "04077": "Pogo plate mechanism fault",
        }
        return _map.get(code, f"Unknown alarm: {code}")


class MotorBoardLOGINResponse(NamedTuple):
    status: int  # 0=success

class MotorBoardVERSIONResponse(NamedTuple):
    version_string: str

class MotorBoardSTATUSResponse(NamedTuple):
    rst: int  # Reset status
    cabin: int  # Chip tray status
    mag: int  # Magnet status
    flu: int  # Fluorescence filter status
    lpush: int  # Left pogo plate status
    rpush: int  # Right pogo plate status
    pmt: int  # PMT status

class MotorBoardCHIP_CABIN_CTRLResponse(NamedTuple):
    status_data: bytes  # Mechanism status, byte[11]=0xFF on error

class MotorBoardCHIP_CABIN_READResponse(NamedTuple):
    status_data: bytes

class MotorBoardMAG_CTRLResponse(NamedTuple):
    status_data: bytes

class MotorBoardMAG_READResponse(NamedTuple):
    status_data: bytes

class MotorBoardPUSHPAD_CTRLResponse(NamedTuple):
    status_data: bytes

class MotorBoardPUSHPAD_READResponse(NamedTuple):
    status_data: bytes

class MotorBoardFLUORESCENCE_CTRLResponse(NamedTuple):
    status_data: bytes

class MotorBoardFLUORESCENCE_READResponse(NamedTuple):
    status_data: bytes

class MotorBoardPMT_CTRLResponse(NamedTuple):
    location: int  # 0xF2=moving, 0xFF=fault

class MotorBoardPMT_READResponse(NamedTuple):
    location: int

class MotorBoardMOTOR_CONTROLResponse(NamedTuple):
    motor_id: int
    position: int

class MotorBoardMOTOR_SPEED_SETResponse(NamedTuple):
    motor_id: int
    speed: int

class MotorBoardMOTOR_POSITION_QUERYResponse(NamedTuple):
    motor_id: int
    position: int

class MotorBoardMOTOR_OPTO_QUERYResponse(NamedTuple):
    sensors: bytes  # 6 motors x 2 sensors

class MotorBoardGET_PARAMSResponse(NamedTuple):
    param_name: str
    value: bytes

class MotorBoardFW_PREPAREResponse(NamedTuple):
    status: int
    result: int

class MotorBoardFW_TRANSFERResponse(NamedTuple):
    status: int
    frame_index_h: int
    frame_index_l: int

class MotorBoardProxy:
    """MotorBoard typed proxy — auto-generated from commands.yaml."""

    def __init__(self, transport: 'DropletBotUart'):
        self._transport = transport

    def reset(self) -> None:
        """MCU software reset"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1100, payload)
        self._transport._w(packet)
        return None

    def login(self, year: int, month: int, day: int, hour: int, minute: int, second: int) -> MotorBoardLOGINResponse | None:
        """Handshake login with timestamp"""
        payload = struct.pack('>BBBBBB', year, month, day, hour, minute, second)
        packet = self._transport._make_cmd_packet(0x1101, payload)
        resp = self._transport._wr(packet, 0x1101, timeout_s=5.0)
        if resp is None:
            return None
        if len(resp) < 1:
            return None
        raw = struct.unpack('>B', resp[:1])
        return MotorBoardLOGINResponse(status=raw[0])

    def version(self) -> MotorBoardVERSIONResponse | None:
        """Get firmware version"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1102, payload)
        resp = self._transport._wr(packet, 0x1102, timeout_s=5.0)
        if resp is None:
            return None
        return MotorBoardVERSIONResponse(version_string=resp.decode('utf-8'))

    def hw_reset(self) -> bool:
        """Hardware reset self-check"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1103, payload)
        return self._transport._wr(packet, 0x1103, timeout_s=30.0) is not None

    def status(self) -> MotorBoardSTATUSResponse | None:
        """Query motor board status"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1104, payload)
        resp = self._transport._wr(packet, 0x1104, timeout_s=3.0)
        if resp is None:
            return None
        if len(resp) < 7:
            return None
        raw = struct.unpack('>BBBBBBB', resp[:7])
        return MotorBoardSTATUSResponse(rst=raw[0], cabin=raw[1], mag=raw[2], flu=raw[3], lpush=raw[4], rpush=raw[5], pmt=raw[6])

    def chip_cabin_ctrl(self, action: int) -> MotorBoardCHIP_CABIN_CTRLResponse | None:
        """Control chip tray position"""
        payload = struct.pack('>B', action)
        packet = self._transport._make_cmd_packet(0x1120, payload)
        resp = self._transport._wr(packet, 0x1120, timeout_s=30.0)
        if resp is None:
            return None
        return MotorBoardCHIP_CABIN_CTRLResponse(status_data=resp[:12])

    def chip_cabin_read(self) -> MotorBoardCHIP_CABIN_READResponse | None:
        """Read chip tray position"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1121, payload)
        resp = self._transport._wr(packet, 0x1121, timeout_s=5.0)
        if resp is None:
            return None
        return MotorBoardCHIP_CABIN_READResponse(status_data=resp[:12])

    def mag_ctrl(self, action: int) -> MotorBoardMAG_CTRLResponse | None:
        """Control magnet position"""
        payload = struct.pack('>B', action)
        packet = self._transport._make_cmd_packet(0x1122, payload)
        resp = self._transport._wr(packet, 0x1122, timeout_s=30.0)
        if resp is None:
            return None
        return MotorBoardMAG_CTRLResponse(status_data=resp[:12])

    def mag_read(self) -> MotorBoardMAG_READResponse | None:
        """Read magnet position"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1123, payload)
        resp = self._transport._wr(packet, 0x1123, timeout_s=5.0)
        if resp is None:
            return None
        return MotorBoardMAG_READResponse(status_data=resp[:12])

    def pushpad_ctrl(self, action: int) -> MotorBoardPUSHPAD_CTRLResponse | None:
        """Control pogo pin plates"""
        payload = struct.pack('>B', action)
        packet = self._transport._make_cmd_packet(0x1124, payload)
        resp = self._transport._wr(packet, 0x1124, timeout_s=30.0)
        if resp is None:
            return None
        return MotorBoardPUSHPAD_CTRLResponse(status_data=resp[:12])

    def pushpad_read(self) -> MotorBoardPUSHPAD_READResponse | None:
        """Read pogo plate position"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1125, payload)
        resp = self._transport._wr(packet, 0x1125, timeout_s=5.0)
        if resp is None:
            return None
        return MotorBoardPUSHPAD_READResponse(status_data=resp[:12])

    def fluorescence_ctrl(self, position: int) -> MotorBoardFLUORESCENCE_CTRLResponse | None:
        """Set fluorescence filter position"""
        payload = struct.pack('>B', position)
        packet = self._transport._make_cmd_packet(0x1126, payload)
        resp = self._transport._wr(packet, 0x1126, timeout_s=60.0)
        if resp is None:
            return None
        return MotorBoardFLUORESCENCE_CTRLResponse(status_data=resp[:12])

    def fluorescence_read(self) -> MotorBoardFLUORESCENCE_READResponse | None:
        """Read fluorescence filter position"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1127, payload)
        resp = self._transport._wr(packet, 0x1127, timeout_s=5.0)
        if resp is None:
            return None
        return MotorBoardFLUORESCENCE_READResponse(status_data=resp[:12])

    def pmt_ctrl(self, position: int) -> MotorBoardPMT_CTRLResponse | None:
        """Move PMT to position"""
        payload = struct.pack('>B', position)
        packet = self._transport._make_cmd_packet(0x1128, payload)
        resp = self._transport._wr(packet, 0x1128, timeout_s=30.0)
        if resp is None:
            return None
        if len(resp) < 1:
            return None
        raw = struct.unpack('>B', resp[:1])
        return MotorBoardPMT_CTRLResponse(location=raw[0])

    def pmt_read(self) -> MotorBoardPMT_READResponse | None:
        """Query PMT position"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1129, payload)
        resp = self._transport._wr(packet, 0x1129, timeout_s=5.0)
        if resp is None:
            return None
        if len(resp) < 1:
            return None
        raw = struct.unpack('>B', resp[:1])
        return MotorBoardPMT_READResponse(location=raw[0])

    def power_ctrl(self, enable: int) -> None:
        """Motor board power control"""
        payload = struct.pack('>B', enable)
        packet = self._transport._make_cmd_packet(0x112A, payload)
        self._transport._w(packet)
        return None

    def fan_ctrl(self, enable: int) -> bool:
        """Motor board fan control"""
        payload = struct.pack('>B', enable)
        packet = self._transport._make_cmd_packet(0x112B, payload)
        return self._transport._wr(packet, 0x112B, timeout_s=2.0) is not None

    def cabin_mag_reset(self) -> bool:
        """Home chip tray and magnet axes"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1130, payload)
        return self._transport._wr(packet, 0x1130, timeout_s=60.0) is not None

    def pmt_reset(self) -> bool:
        """Home PMT motor"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1131, payload)
        return self._transport._wr(packet, 0x1131, timeout_s=30.0) is not None

    def flu_reset(self) -> bool:
        """Home fluorescence filter"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1132, payload)
        return self._transport._wr(packet, 0x1132, timeout_s=30.0) is not None

    def pushpad_reset(self) -> bool:
        """Home pogo pin plates"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1133, payload)
        return self._transport._wr(packet, 0x1133, timeout_s=30.0) is not None

    def pmt_mt_speed_set(self, speed: int) -> bool:
        """Set PMT motor speed"""
        payload = struct.pack('>i', speed)
        packet = self._transport._make_cmd_packet(0x1141, payload)
        return self._transport._wr(packet, 0x1141, timeout_s=2.0) is not None

    def motor_control(self, motor_id: int, action: int, distance: int) -> MotorBoardMOTOR_CONTROLResponse | None:
        """Motor control — move, stop, home"""
        payload = struct.pack('>BBi', motor_id, action, distance)
        packet = self._transport._make_cmd_packet(0x11B0, payload)
        resp = self._transport._wr(packet, 0x11B0, timeout_s=30.0)
        if resp is None:
            return None
        if len(resp) < 5:
            return None
        raw = struct.unpack('>Bi', resp[:5])
        return MotorBoardMOTOR_CONTROLResponse(motor_id=raw[0], position=raw[1])

    def motor_speed_set(self, motor_id: int, speed: int) -> MotorBoardMOTOR_SPEED_SETResponse | None:
        """Set motor speed"""
        payload = struct.pack('>Bi', motor_id, speed)
        packet = self._transport._make_cmd_packet(0x11B1, payload)
        resp = self._transport._wr(packet, 0x11B1, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 5:
            return None
        raw = struct.unpack('>Bi', resp[:5])
        return MotorBoardMOTOR_SPEED_SETResponse(motor_id=raw[0], speed=raw[1])

    def motor_position_query(self, motor_id: int) -> MotorBoardMOTOR_POSITION_QUERYResponse | None:
        """Query motor position"""
        payload = struct.pack('>B', motor_id)
        packet = self._transport._make_cmd_packet(0x11B3, payload)
        resp = self._transport._wr(packet, 0x11B3, timeout_s=2.0)
        if resp is None:
            return None
        if len(resp) < 5:
            return None
        raw = struct.unpack('>Bi', resp[:5])
        return MotorBoardMOTOR_POSITION_QUERYResponse(motor_id=raw[0], position=raw[1])

    def motor_opto_query(self) -> MotorBoardMOTOR_OPTO_QUERYResponse | None:
        """Query all motor opto-coupler sensors"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x11B4, payload)
        resp = self._transport._wr(packet, 0x11B4, timeout_s=2.0)
        if resp is None:
            return None
        return MotorBoardMOTOR_OPTO_QUERYResponse(sensors=resp[:12])

    def set_params(self, param_name: str, value: bytes) -> bool:
        """Write parameter"""
        payload = param_name.encode('utf-8') + b'\x00'
        payload += value
        packet = self._transport._make_cmd_packet(0x1160, payload)
        return self._transport._wr(packet, 0x1160, timeout_s=3.0) is not None

    def get_params(self, param_name: str) -> MotorBoardGET_PARAMSResponse | None:
        """Read parameter"""
        payload = param_name.encode('utf-8') + b'\x00'
        packet = self._transport._make_cmd_packet(0x1161, payload)
        resp = self._transport._wr(packet, 0x1161, timeout_s=5.0)
        if resp is None:
            return None
        parts = resp.split(b'\x00', 1)
        if len(parts) == 2:
            return MotorBoardGET_PARAMSResponse(param_name=parts[0].decode('utf-8'), value=parts[1])
        return None

    def preset_params(self) -> bool:
        """Save all parameters to flash"""
        payload = b''
        packet = self._transport._make_cmd_packet(0x1162, payload)
        return self._transport._wr(packet, 0x1162, timeout_s=5.0) is not None

    def set_alarm_level(self, level: int) -> bool:
        """Set alarm reporting level"""
        payload = struct.pack('>B', level)
        packet = self._transport._make_cmd_packet(0x1173, payload)
        return self._transport._wr(packet, 0x1173, timeout_s=2.0) is not None

    def clear_alarm(self, alarm_code: bytes) -> bool:
        """Clear/confirm alarm by code"""
        payload = struct.pack('>5s', alarm_code)
        packet = self._transport._make_cmd_packet(0x1174, payload)
        return self._transport._wr(packet, 0x1174, timeout_s=2.0) is not None

    def set_log_level(self, level: int) -> bool:
        """Set log reporting level"""
        payload = struct.pack('>B', level)
        packet = self._transport._make_cmd_packet(0x1171, payload)
        return self._transport._wr(packet, 0x1171, timeout_s=2.0) is not None

    def fw_prepare(self, module_id: int = 0, upgrade_type: int = 1) -> MotorBoardFW_PREPAREResponse | None:
        """Firmware upgrade handshake"""
        payload = struct.pack('>BB', module_id, upgrade_type)
        packet = self._transport._make_cmd_packet(0x1180, payload)
        resp = self._transport._wr(packet, 0x1180, timeout_s=60.0)
        if resp is None:
            return None
        if len(resp) < 2:
            return None
        raw = struct.unpack('>BB', resp[:2])
        return MotorBoardFW_PREPAREResponse(status=raw[0], result=raw[1])

    def fw_transfer(self, module_id: int, total_frames: int, frame_index: int, data: bytes) -> MotorBoardFW_TRANSFERResponse | None:
        """Firmware data transfer"""
        payload = struct.pack('>BHH', module_id, total_frames, frame_index)
        payload += data
        packet = self._transport._make_cmd_packet(0x1181, payload)
        resp = self._transport._wr(packet, 0x1181, timeout_s=30.0)
        if resp is None:
            return None
        if len(resp) < 3:
            return None
        raw = struct.unpack('>BBB', resp[:3])
        return MotorBoardFW_TRANSFERResponse(status=raw[0], frame_index_h=raw[1], frame_index_l=raw[2])
