# AUTO-GENERATED by gen_python_commands.py — DO NOT EDIT
# Generated: 2026-09-01T12:41:56
#
# This file is regenerated every firmware build. Import it in your driver
# to get up-to-date command IDs, handler mappings, and parameter lists.
# If a command appears in MISSING_BINDINGS, it needs a Python method.
#   DroSIG firmware: DroSIG_1.0.1.26-8-g724f7a9
#   DroDri firmware: DroDri_1.0.0.19-6-g845a12f-dirty

# Standard library imports.
from enum import IntEnum

DroSIG_FW_VERSION = "DroSIG_1.0.1.26-8-g724f7a9"  # firmware this was generated from
DroDri_FW_VERSION = "DroDri_1.0.0.19-6-g845a12f-dirty"  # firmware this was generated from

class DroSIGCmd(IntEnum):
    """Command IDs for DroSIG board (head=0x12)."""
    CMD_RESET = 0x1200  # MCU reset command
    CMD_LOGIN = 0x1201  # login command
    CMD_VERSION = 0x1202  # get version
    CMD_HW_RESET = 0x1203  # HW reset self-test
    CMD_STATUS = 0x1204  # query system status
    CMD_DATA_REPORT = 0x1205  # data report
    CMD_TEMP_SET_TARGET = 0x1210  # set target temp
    CMD_TEMP_START_STOP = 0x1211  # set temp control switch
    CMD_TEMP_READ_INFO = 0x1212  # get temp info
    CMD_TEMP_READ_PARAMS = 0x1213  # get temp control params
    CMD_TEMP_SET_PARAMS = 0x1214  # set temp control params
    CMD_ELECTRODE_STATE_READ = 0x1220  # read back current electrode channels
    CMD_RGB_LIGHT_CTRL = 0x1221  # set indicator LED status
    CMD_ILLUMINATION_CTRL = 0x1222  # set illumination LED brightness
    CMD_FLUORESCENCE_CTRL = 0x1223  # set LED brightness
    CMD_ELECTRODE_SET_VOLT = 0x1224  # set HV signal
    CMD_ELECTRODE_STATE = 0x1225  # set electrode channels (HC595 bitmap)
    CMD_ELECTRODE_SET_FREQ = 0x1226  # set HV signal
    CMD_PMT_ACQUIRE_START = 0x1227  # PMT data read
    CMD_PMT_DATA_REPORT = 0x1228  # PMT data upload
    CMD_PMT_GAIN_SET = 0x1229  # PMT gain setting
    CMD_PMT_STATUS_REPORT = 0x122A  # PMT heartbeat
    CMD_PMT_POWER = 0x122B  # PMT power control
    CMD_PMT_START_DEBUG = 0x122C  # PMT start debug
    CMD_PMT_STOP_DEBUG = 0x122D  # PMT stop debug
    CMD_PMT_DATA_UPLOAD_DEBUG = 0x122E  # PMT detailed debug data upload
    CMD_MEASURE_CAPACITANCE = 0x122F  # On-demand capacitance of active electrodes
    CMD_HV_TEST = 0x1233  # report power status
    CMD_HV_ENABLE = 0x1234  # master HV output enable (pad-gated); arg2=bypass
    CMD_CHANNEL_CAPACITANCES = 0x1235  # Per-channel capacitance (no HV change)
    CMD_RAW_ADC_CAP = 0x1236  # Raw ADC samples from capacitance feedback
    CMD_CAP_CALIBRATE_BIAS = 0x1237  # Calibrate capacitance DC bias
    CMD_SET_BOOT_5V_DELAY = 0x1238  # Set 5V boot delay (ms) in EasyFlash
    CMD_CAP_AUTORANGE = 0x1239  # Configure capacitance autorange
    CMD_READ_VREF = 0x123A  # Read voltage divider reference (PC4)
    CMD_SPI_ADC_DIAG = 0x123B  # SPI ADC diagnostic
    CMD_CAP_SET_MODE = 0x123C  # Set cap measurement mode (IQR/VREF)
    CMD_CAP_CROSS_CAL = 0x123D  # Cross-calibrate BACK1/BACK2 from electrodes
    CMD_PMT_STREAM = 0x123E  # PMT live streaming start/stop (data[0]=1/0)
    CMD_PMT_STREAM_DATA = 0x123F  # PMT live stream data packets (outbound only)
    CMD_BOARD_CHANNELS_GET = 0x1240  # get provisioned channel count + n_chips
    CMD_BOARD_CHANNELS_SET = 0x1241  # provision channel count (120 or 200)
    CMD_ELECTRODE_STATE_CH = 0x1242  # set electrodes via channel-indexed bitmap
    CMD_ELECTRODE_STATE_READ_CH = 0x1243  # read electrodes as channel-indexed bitmap
    CMD_SHORT_DETECT_CH = 0x1244  # short detect over a channel subset (0=all)
    CMD_READ_UID = 0x1245  # read STM32 96-bit factory UID (12 bytes)
    CMD_APP_BAUD_GET = 0x1246  # read current app UART baud (u32 BE)
    CMD_APP_BAUD_SET = 0x1247  # set app UART baud (u32 BE, whitelist), effective after reboot
    CMD_CAL_CAPS_GET = 0x1248  # get multi-slope reference-cap count (3 or 5)
    CMD_CAL_CAPS_SET = 0x1249  # set multi-slope reference-cap count (3 or 5), persisted
    CMD_CAP_CALIBRATE_ML = 0x124A  # run multi-slope 3-level calibration; arg [u16 BE hv_mv], 0=default
    CMD_CAP_ML_GET = 0x124B  # read fitted multi-slope params for a level; arg [u8 level 0-2]
    CMD_CAN_RECOVER = 0x124C  # re-init MCU CAN after a motor warm-reset (clears bus-off, re-syncs); call after motor settles
    CMD_CAN_DIAG = 0x124D  # read-only CAN routing/TX/RX debug counters
    CMD_CAP_ML_REALTIME = 0x124E  # get/set ML-fitted realtime cap path; req [u8 0xFF=query|0/1=set], resp [u8 current]
    CMD_CAP_ELEC_GAIN = 0x124F  # get/set electrode-path gain permille (EF-persisted); req [u16 BE, 0=query], resp [u16 BE current]
    CMD_PAD_ENGAGE = 0x1250  # engage/retract pads (classic|smart); async reply on completion
    CMD_PAD_SENS_READ = 0x1251  # read raw pad-contact sensors (immediate)
    CMD_RAILS_CYCLE = 0x1252  # atomic rails power-cycle; immediate ACK then self-reset
    CMD_SET_PARAMS = 0x1260  # param set
    CMD_GET_PARAMS = 0x1261  # param read
    CMD_PRESET_PARAMS = 0x1262  # param prestore
    CMD_GET_PARAMS_FLASH = 0x1263  # param read straight from EasyFlash (persistence proof)
    CMD_REPORT_LOG = 0x1270  # log report
    CMD_SET_LOG_LEVEL = 0x1271  # log report level setting
    CMD_REPORT_ALARM = 0x1272  # alarm report
    CMD_SET_ALARM_LEVEL = 0x1273  # alarm level setting
    CMD_CLEAR_ALARM = 0x1274  # alarm clear [fix #8: was 0x73, collided with SET_ALARM_LEVEL]
    CMD_GET_ALARMS = 0x1275  # list active (latched) alarms
    CMD_FW_PREPARE = 0x1280  # upgrade handshake
    CMD_FW_TRANSFER = 0x1281  # firmware upgrade
    CMD_FW_RESULT = 0x1282  # upgrade result
    CMD_SET_REPORT_CYCLE = 0x12F6  # data report period setting
    CMD_SET_REPORT_CYCLE2 = 0x12F7  # data report period setting2

DROSIG_HANDLERS = {
    0x1274: {"end": 0x1274, "handler": 'alarm_confirm', "file": 'alarm.c'},
    0x1275: {"end": 0x1275, "handler": 'alarm_get_active', "file": 'alarm.c'},
    0x1250: {"end": 0x1250, "handler": 'pad_engage_server', "file": 'business/pad_engage.c'},
    0x1251: {"end": 0x1251, "handler": 'pad_sens_read_server', "file": 'business/pad_engage.c'},
    'SIG_REQ_MOTOR_CTRL': {"end": 'SIG_REQ_MOTOR_CTRL', "handler": 'pad_motor_reply_server', "file": 'business/pad_engage.c'},
    'SIG_REQ_PUSHPAD_CTRL': {"end": 'SIG_REQ_PUSHPAD_CTRL', "handler": 'pad_pushpad_reply_server', "file": 'business/pad_engage.c'},
    0x1244: {"end": 0x1244, "handler": 'short_detect_ch_server', "file": 'business/short_circuit_detection.c'},
    'CMD_READ_TEMP_SENSORS': {"end": 'CMD_READ_TEMP_SENSORS', "handler": 'debug_get_temp_sensor_info', "file": 'business/debug_server.c'},
    'CMD_TEMP_HEAT_PWM': {"end": 'CMD_TEMP_HEAT_PWM', "handler": 'debug_temp_pwm_duty', "file": 'business/debug_server.c'},
    'CMD_BUZZER_CTRL': {"end": 'CMD_BUZZER_CTRL', "handler": 'debug_beep', "file": 'business/debug_server.c'},
    'CMD_FAN_CTRL': {"end": 'CMD_FAN_CTRL', "handler": 'debug_set_fan', "file": 'business/debug_server.c'},
    'CMD_POWER_CTRL': {"end": 'CMD_POWER_CTRL', "handler": 'debug_power_ctrl', "file": 'business/debug_server.c'},
    'CMD_READ_ADC_DATA': {"end": 'CMD_READ_ADC_DATA', "handler": 'debug_adc_read', "file": 'business/debug_server.c'},
    0x123B: {"end": 0x123B, "handler": 'spi_adc_diag_server', "file": 'business/debug_server.c'},
    'CMD_CAP_MATCH': {"end": 'CMD_CAP_MATCH', "handler": 'debug_cap_match', "file": 'business/debug_server.c'},
    'CMD_HV_PWM_FREQ': {"end": 'CMD_HV_PWM_FREQ', "handler": 'debug_pwm_freq', "file": 'business/debug_server.c'},
    'CMD_HV_VALUE': {"end": 'CMD_HV_VALUE', "handler": 'debug_hv_value', "file": 'business/debug_server.c'},
    'CMD_DDS_POT': {"end": 'CMD_DDS_POT', "handler": 'debug_dds_pot', "file": 'business/debug_server.c'},
    'CMD_DDS_WAVE': {"end": 'CMD_DDS_WAVE', "handler": 'debug_dds_config', "file": 'business/debug_server.c'},
    'CMD_DAC_SET_VOLT': {"end": 'CMD_DAC_SET_VOLT', "handler": 'debug_dac_voltage_set', "file": 'business/debug_server.c'},
    'CMD_LOADED_SHORT_DETECT': {"end": 'CMD_LOADED_SHORT_DETECT', "handler": 'debug_inplace_short_detect', "file": 'business/debug_server.c'},
    'CMD_SHORT_CIRCUIT_DETECT': {"end": 'CMD_SHORT_CIRCUIT_DETECT', "handler": 'debug_short_circuit_detect', "file": 'business/debug_server.c'},
    'CMD_CAN_RX_DIAG': {"end": 'CMD_CAN_RX_DIAG', "handler": 'debug_can_rx_diag', "file": 'business/debug_server.c'},
    0x1245: {"end": 0x1245, "handler": 'debug_read_uid', "file": 'business/debug_server.c'},
    0x1240: {"end": 0x1240, "handler": 'board_channels_get_server', "file": 'business/debug_server.c'},
    0x1241: {"end": 0x1241, "handler": 'board_channels_set_server', "file": 'business/debug_server.c'},
    0x1248: {"end": 0x1248, "handler": 'cal_caps_get_server', "file": 'business/debug_server.c'},
    0x1249: {"end": 0x1249, "handler": 'cal_caps_set_server', "file": 'business/debug_server.c'},
    0x1252: {"end": 0x1252, "handler": 'rails_cycle_server', "file": 'business/power.c'},
    0x1225: {"end": 0x1225, "handler": 'droplet_move_server', "file": 'business/droplet_move.c'},
    0x1242: {"end": 0x1242, "handler": 'droplet_move_server_ch', "file": 'business/droplet_move.c'},
    0x1220: {"end": 0x1220, "handler": 'electrode_state_read_server', "file": 'business/droplet_move.c'},
    0x1243: {"end": 0x1243, "handler": 'electrode_state_read_ch_server', "file": 'business/droplet_move.c'},
    0x1227: {"end": 0x1227, "handler": 'pmt_main_server', "file": 'business/pmt.c'},
    0x1229: {"end": 0x1229, "handler": 'pmt_gain_server', "file": 'business/pmt.c'},
    0x122B: {"end": 0x122B, "handler": 'pmt_power_server', "file": 'business/pmt.c'},
    'SIG_REQ_PMT_MT_CTRL': {"end": 'SIG_REQ_PMT_MT_CTRL', "handler": 'pmt_driver_server', "file": 'business/pmt.c'},
    0x122C: {"end": 0x122C, "handler": 'pmt_debug_start_server', "file": 'business/pmt.c'},
    0x123E: {"end": 0x123E, "handler": 'pmt_stream_server', "file": 'business/pmt.c'},
    0x122D: {"end": 0x122D, "handler": 'pmt_debug_stop_server', "file": 'business/pmt.c'},
    0x122E: {"end": 0x122E, "handler": 'pmt_debug_upload_server', "file": 'business/pmt.c'},
    0x1221: {"end": 0x1221, "handler": 'rgy_led_server', "file": 'business/extern_server.c'},
    0x1222: {"end": 0x1222, "handler": 'light_lamp_server', "file": 'business/extern_server.c'},
    0x1223: {"end": 0x1223, "handler": 'flu_led_server', "file": 'business/extern_server.c'},
    0x1224: {"end": 0x1224, "handler": 'hv_signal_server', "file": 'business/extern_server.c'},
    0x1226: {"end": 0x1226, "handler": 'hv_signal_freq', "file": 'business/extern_server.c'},
    0x1230: {"end": 0x1230, "handler": 'cap_short_detect_server', "file": 'business/extern_server.c'},
    0x1231: {"end": 0x1231, "handler": 'cap_cali_server', "file": 'business/extern_server.c'},
    0x1232: {"end": 0x1232, "handler": 'cap_detect_server', "file": 'business/extern_server.c'},
    0x1233: {"end": 0x1233, "handler": 'vol_check_server', "file": 'business/extern_server.c'},
    0x122F: {"end": 0x122F, "handler": 'measure_capacitance_server', "file": 'business/extern_server.c'},
    0x1235: {"end": 0x1235, "handler": 'channel_capacitances_server', "file": 'business/extern_server.c'},
    0x1236: {"end": 0x1236, "handler": 'raw_adc_cap_server', "file": 'business/extern_server.c'},
    0x1237: {"end": 0x1237, "handler": 'cap_calibrate_bias_server', "file": 'business/extern_server.c'},
    0x1239: {"end": 0x1239, "handler": 'cap_autorange_server', "file": 'business/extern_server.c'},
    0x123A: {"end": 0x123A, "handler": 'vref_read_server', "file": 'business/extern_server.c'},
    0x123C: {"end": 0x123C, "handler": 'cap_set_mode_server', "file": 'business/extern_server.c'},
    0x124A: {"end": 0x124A, "handler": 'cap_calibrate_ml_server', "file": 'business/extern_server.c'},
    0x124B: {"end": 0x124B, "handler": 'cap_ml_get_server', "file": 'business/extern_server.c'},
    0x124C: {"end": 0x124C, "handler": 'can_recover_server', "file": 'business/extern_server.c'},
    0x124D: {"end": 0x124D, "handler": 'can_diag_server', "file": 'business/extern_server.c'},
    0x124E: {"end": 0x124E, "handler": 'cap_ml_realtime_server', "file": 'business/extern_server.c'},
    0x124F: {"end": 0x124F, "handler": 'cap_elec_gain_server', "file": 'business/extern_server.c'},
    0x123D: {"end": 0x123D, "handler": 'cap_cross_cal_server', "file": 'business/extern_server.c'},
    0x1238: {"end": 0x1238, "handler": 'set_boot_5v_delay_server', "file": 'business/extern_server.c'},
    0x1246: {"end": 0x1246, "handler": 'app_baud_get_server', "file": 'business/Miscellaneous/app_baud.c'},
    0x1247: {"end": 0x1247, "handler": 'app_baud_set_server', "file": 'business/Miscellaneous/app_baud.c'},
    0x1260: {"end": 0x1263, "handler": 'dp_server', "file": 'business/param/param.c'},
    0x1210: {"end": 0x1214, "handler": 'temp_server', "file": 'tempctrl/tempctrl.c'},
    0x1234: {"end": 0x1234, "handler": 'hv_enable_server', "file": 'sysserver/sys_status.c'},
    0x1204: {"end": 0x1204, "handler": 'sys_status', "file": 'sysserver/sys_status.c'},
    0x12F6: {"end": 0x12F6, "handler": 'set_report_cycle', "file": 'sysserver/sys_status.c'},
    0x12F7: {"end": 0x12F7, "handler": 'set_report_interval', "file": 'sysserver/sys_status.c'},
    0x1201: {"end": 0x1203, "handler": 'system_cmd', "file": 'sysserver/system_server.c'},
    0x1200: {"end": 0x1200, "handler": 'hw_cpu_reset', "file": 'sysserver/system_server.c'},
    0x1280: {"end": 0x1280, "handler": 'update0', "file": 'sysserver/system_server.c'},
}

DROSIG_PARAMS = [
    '_dp_model',
    'g_temp_params',
    'g_temp_params2',
]

DROSIG_HEAD = 0x12

class DroDriCmd(IntEnum):
    """Command IDs for DroDri board (head=0x11)."""
    CMD_RESET = 0x1100  # MCU reset command
    CMD_LOGIN = 0x1101  # Login command
    CMD_VERSION = 0x1102  # Get version
    CMD_HW_RESET = 0x1103  # Hardware reset self-check
    CMD_STATUS = 0x1104  # Get system status
    CMD_DATA_REPORT = 0x1105  # Data report
    CMD_CHIP_CABIN_CTRL = 0x1120  # Chip tray control
    CMD_CHIP_CABIN_READ = 0x1121  # Chip tray read
    CMD_MAG_CTRL = 0x1122  # Magnet control
    CMD_MAG_READ = 0x1123  # Magnet read
    CMD_PUSHPAD_CTRL = 0x1124  # Pogo pin plate control
    CMD_PUSHPAD_READ = 0x1125  # Pogo pin plate read
    CMD_FLUORESCENCE_CTRL = 0x1126  # Fluorescence filter control
    CMD_FLUORESCENCE_READ = 0x1127  # Fluorescence filter read
    CMD_PMT_CTRL = 0x1128  # PMT position control
    CMD_PMT_READ = 0x1129  # PMT position read
    CMD_POWER_CTRL = 0x112A  # Power control
    CMD_FAN_CTRL = 0x112B  # Fan control
    CMD_CABIN_MAG_RESET = 0x1130  # Chip tray & magnet reset
    CMD_PMT_RESET = 0x1131  # PMT reset
    CMD_FLU_RESET = 0x1132  # Fluorescence filter reset
    CMD_PUSHPAD_RESET = 0x1133  # Pogo pin plate reset
    CMD_MAG_RESET = 0x1134  # Magnet-only home (2026-08-01)
    CMD_PMT_MT_CTRL = 0x1140  # PMT motor control
    CMD_PMT_MT_SPEED_SET = 0x1141  # PMTMotor speed setting
    CMD_READ_UID = 0x1145  # read STM32 96-bit factory UID (12 bytes)
    CMD_SET_PARAMS = 0x1160  # Set parameter
    CMD_GET_PARAMS = 0x1161  # Get parameter
    CMD_PRESET_PARAMS = 0x1162  # Save parameter
    CMD_GET_PARAMS_FLASH = 0x1163  # Get parameter straight from EasyFlash (persistence proof)
    CMD_REPORT_LOG = 0x1170  # Log report
    CMD_SET_LOG_LEVEL = 0x1171  # Log level setting
    CMD_REPORT_ALARM = 0x1172  # Alarm report
    CMD_SET_ALARM_LEVEL = 0x1173  # Alarm level setting
    CMD_CLEAR_ALARM = 0x1174  # Alarm clear [fix #8: was 0x73, collided with SET_ALARM_LEVEL]
    CMD_GET_ALARMS = 0x1175  # List active (latched) alarms
    CMD_FW_PREPARE = 0x1180  # Upgrade handshake
    CMD_FW_TRANSFER = 0x1181  # Firmware upgrade
    CMD_FW_RESULT = 0x1182  # Upgrade result
    CMD_MOTOR_CONTROL = 0x11B0  # Motor control command
    CMD_MOTOR_SPEED_SET = 0x11B1  # Motor speed setting
    CMD_MOTOR_POSITION_QUERY = 0x11B3  # Get motor position
    CMD_MOTOR_OPTO_QUERY = 0x11B4  # Get all optical switch states
    CMD_MOTOR_HOMED_QUERY = 0x11B5  # Get per-motor homed status (bitmap)
    CMD_MOTOR_ESTOP = 0x11B6  # Emergency stop, all axes
    CMD_MOTOR_RECOVERY = 0x11B7  # Un-homed/faulted jog mode (auto-expires)
    CMD_TMC_CTRL = 0x11B8  # Per-axis StealthChop / GLOBAL_SCALER / telemetry
    CMD_SET_REPORT_CYCLE = 0x11F6  # Data report cycle setting
    CMD_SET_REPORT_CYCLE2 = 0x11F7  # Data report cycle setting 2

DRODRI_HANDLERS = {
    0x1174: {"end": 0x1174, "handler": 'alarm_confirm', "file": 'alarm.c'},
    0x1175: {"end": 0x1175, "handler": 'alarm_get_active', "file": 'alarm.c'},
    0x11B4: {"end": 0x11B4, "handler": 'mt_opt_read_server', "file": 'business/server_init.c'},
    0x1145: {"end": 0x1145, "handler": 'mt_read_uid_server', "file": 'business/server_init.c'},
    0x11B0: {"end": 0x11B3, "handler": 'mt_cmd_reav', "file": 'business/mt_cmd.c'},
    0x11B5: {"end": 0x11B5, "handler": 'mt_homed_query_server', "file": 'business/mt_cmd.c'},
    0x11B6: {"end": 0x11B6, "handler": 'mt_estop_server', "file": 'business/mt_cmd.c'},
    0x11B7: {"end": 0x11B7, "handler": 'mt_recovery_server', "file": 'business/mt_cmd.c'},
    0x11B8: {"end": 0x11B8, "handler": 'mt_tmc_ctrl_server', "file": 'business/mt_cmd.c'},
    0x1126: {"end": 0x1127, "handler": 'flu_cmd_deal', "file": 'business/fluorescence.c'},
    0x1132: {"end": 0x1132, "handler": 'flu_reset_server', "file": 'business/fluorescence.c'},
    0x1124: {"end": 0x1125, "handler": 'mc_pushpad_server', "file": 'business/motion_coord.c'},
    0x1122: {"end": 0x1123, "handler": 'mc_mag_server', "file": 'business/motion_coord.c'},
    0x1120: {"end": 0x1121, "handler": 'mc_cabin_server', "file": 'business/motion_coord.c'},
    0x1133: {"end": 0x1133, "handler": 'mc_pushpad_reset_server', "file": 'business/motion_coord.c'},
    0x1130: {"end": 0x1130, "handler": 'mc_cabin_mag_reset_server', "file": 'business/motion_coord.c'},
    0x1134: {"end": 0x1134, "handler": 'mc_mag_reset_server', "file": 'business/motion_coord.c'},
    0x1128: {"end": 0x1129, "handler": 'pmt_cmd_deal', "file": 'business/pmt.c'},
    0x1140: {"end": 0x1140, "handler": 'pmt_cmd_deal', "file": 'business/pmt.c'},
    0x1141: {"end": 0x1141, "handler": 'pmt_set_spd', "file": 'business/pmt.c'},
    0x1131: {"end": 0x1131, "handler": 'pmt_reset_server', "file": 'business/pmt.c'},
    0x1160: {"end": 0x1163, "handler": 'dp_server', "file": 'business/param/param.c'},
    0x1104: {"end": 0x1104, "handler": 'sys_status', "file": 'sysserver/sys_status.c'},
    0x112A: {"end": 0x112A, "handler": 'power_ctrl_server', "file": 'sysserver/sys_status.c'},
    0x112B: {"end": 0x112B, "handler": 'fan_ctrl_server', "file": 'sysserver/sys_status.c'},
    0x1101: {"end": 0x1103, "handler": 'system_cmd', "file": 'sysserver/system_server.c'},
    0x1100: {"end": 0x1100, "handler": 'hw_cpu_reset', "file": 'sysserver/system_server.c'},
    0x1180: {"end": 0x1180, "handler": 'update', "file": 'sysserver/system_server.c'},
}

DRODRI_PARAMS = [
    '_dp_chip',
    '_dp_flu',
    '_dp_magnet',
    '_dp_model',
    '_dp_pmt',
    '_dp_pushpad',
    '_dp_temp',
    '_dp_tpos',
    '_dp_ydir',
    '_mt_cabin_dp',
    '_mt_flu_dp',
    '_mt_padl_dp',
    '_mt_padr_dp',
    '_mt_y_dp',
    '_mt_z_dp',
]

DRODRI_HEAD = 0x11

# Commands registered in firmware but missing Python method bindings.
# Add a method in portable_dropbot_service.py for each of these.
MISSING_BINDINGS = [
    0x1134,  # CMD_MAG_RESET — handler: mc_mag_reset_server in business/motion_coord.c
    0x1140,  # CMD_PMT_MT_CTRL — handler: pmt_cmd_deal in business/pmt.c
    0x1145,  # CMD_READ_UID — handler: mt_read_uid_server in business/server_init.c
    0x1161,  # CMD_GET_PARAMS — handler: dp_server in business/param/param.c
    0x1162,  # CMD_PRESET_PARAMS — handler: dp_server in business/param/param.c
    0x1163,  # CMD_GET_PARAMS_FLASH — handler: dp_server in business/param/param.c
    0x1175,  # CMD_GET_ALARMS — handler: alarm_get_active in alarm.c
    0x11B2,  # UNKNOWN_0x11B2 — handler: mt_cmd_reav in business/mt_cmd.c
    0x11B6,  # CMD_MOTOR_ESTOP — handler: mt_estop_server in business/mt_cmd.c
    0x11B7,  # CMD_MOTOR_RECOVERY — handler: mt_recovery_server in business/mt_cmd.c
    0x11B8,  # CMD_TMC_CTRL — handler: mt_tmc_ctrl_server in business/mt_cmd.c
    0x1220,  # CMD_ELECTRODE_STATE_READ — handler: electrode_state_read_server in business/droplet_move.c
    0x122F,  # CMD_MEASURE_CAPACITANCE — handler: measure_capacitance_server in business/extern_server.c
    0x1234,  # CMD_HV_ENABLE — handler: hv_enable_server in sysserver/sys_status.c
    0x1235,  # CMD_CHANNEL_CAPACITANCES — handler: channel_capacitances_server in business/extern_server.c
    0x1236,  # CMD_RAW_ADC_CAP — handler: raw_adc_cap_server in business/extern_server.c
    0x1237,  # CMD_CAP_CALIBRATE_BIAS — handler: cap_calibrate_bias_server in business/extern_server.c
    0x1238,  # CMD_SET_BOOT_5V_DELAY — handler: set_boot_5v_delay_server in business/extern_server.c
    0x1239,  # CMD_CAP_AUTORANGE — handler: cap_autorange_server in business/extern_server.c
    0x123A,  # CMD_READ_VREF — handler: vref_read_server in business/extern_server.c
    0x123B,  # CMD_SPI_ADC_DIAG — handler: spi_adc_diag_server in business/debug_server.c
    0x123C,  # CMD_CAP_SET_MODE — handler: cap_set_mode_server in business/extern_server.c
    0x123D,  # CMD_CAP_CROSS_CAL — handler: cap_cross_cal_server in business/extern_server.c
    0x123E,  # CMD_PMT_STREAM — handler: pmt_stream_server in business/pmt.c
    0x1240,  # CMD_BOARD_CHANNELS_GET — handler: board_channels_get_server in business/debug_server.c
    0x1241,  # CMD_BOARD_CHANNELS_SET — handler: board_channels_set_server in business/debug_server.c
    0x1242,  # CMD_ELECTRODE_STATE_CH — handler: droplet_move_server_ch in business/droplet_move.c
    0x1243,  # CMD_ELECTRODE_STATE_READ_CH — handler: electrode_state_read_ch_server in business/droplet_move.c
    0x1244,  # CMD_SHORT_DETECT_CH — handler: short_detect_ch_server in business/short_circuit_detection.c
    0x1245,  # CMD_READ_UID — handler: debug_read_uid in business/debug_server.c
    0x1246,  # CMD_APP_BAUD_GET — handler: app_baud_get_server in business/Miscellaneous/app_baud.c
    0x1247,  # CMD_APP_BAUD_SET — handler: app_baud_set_server in business/Miscellaneous/app_baud.c
    0x1248,  # CMD_CAL_CAPS_GET — handler: cal_caps_get_server in business/debug_server.c
    0x1249,  # CMD_CAL_CAPS_SET — handler: cal_caps_set_server in business/debug_server.c
    0x124A,  # CMD_CAP_CALIBRATE_ML — handler: cap_calibrate_ml_server in business/extern_server.c
    0x124B,  # CMD_CAP_ML_GET — handler: cap_ml_get_server in business/extern_server.c
    0x124C,  # CMD_CAN_RECOVER — handler: can_recover_server in business/extern_server.c
    0x124D,  # CMD_CAN_DIAG — handler: can_diag_server in business/extern_server.c
    0x124E,  # CMD_CAP_ML_REALTIME — handler: cap_ml_realtime_server in business/extern_server.c
    0x124F,  # CMD_CAP_ELEC_GAIN — handler: cap_elec_gain_server in business/extern_server.c
    0x1250,  # CMD_PAD_ENGAGE — handler: pad_engage_server in business/pad_engage.c
    0x1251,  # CMD_PAD_SENS_READ — handler: pad_sens_read_server in business/pad_engage.c
    0x1252,  # CMD_RAILS_CYCLE — handler: rails_cycle_server in business/power.c
    0x1261,  # CMD_GET_PARAMS — handler: dp_server in business/param/param.c
    0x1262,  # CMD_PRESET_PARAMS — handler: dp_server in business/param/param.c
    0x1263,  # CMD_GET_PARAMS_FLASH — handler: dp_server in business/param/param.c
    0x1275,  # CMD_GET_ALARMS — handler: alarm_get_active in alarm.c
]

# Summary: 108 firmware commands, 84 Python bindings, 47 missing
